### ISSUE TITLE
无法与KDE Plasma兼容

### ISSUE THREAD

**Issue by vzxxbacq** [countstarlight/deepin-wine-wechat-arch#1]
OS: Manjaro KDE 18
运行闪退，Log如下：
```
rm: 无法删除'/home/$USER/.deepinwine/Deepin-WeChat/drive_c/users/fhq/Application Data/Tencent/WeChat/All Users/config/configEx.ini': 没有那个文件或目录
```
请问有机会修改成功吗？如何修改呢？

**Comment by countstarlight** [comment]
收到，明天我去测试一下

**Comment by countstarlight** [comment]
@vzxxbacq 我在新装的archlinux + kde上测试，没有遇到这个问题，你确定安装的是[deepin-wine-wechat](https://aur.archlinux.org/packages/deepin-wine-wechat/)吗？
