### ISSUE TITLE
manjaro kde桌面来信息没有通知

### ISSUE THREAD

**Issue by z2x** [countstarlight/deepin-wine-wechat-arch#10]
manjaro kde桌面来信息时没有通知，只有声音，
版本：
4.19.28-1-MANJARO #1 SMP PREEMPT Sun Mar 10 08:32:42 UTC 2019

**Comment by kmvan** [comment]
Xfce 有时候也会。而且托盘图标很叠加在输入法图标上面，
![image](https://user-images.githubusercontent.com/3839554/54881759-2c799980-4e8e-11e9-8a87-12f1c001d16d.png)

**Comment by countstarlight** [comment]
Archlinux + kde也是来消息只有提示音，这个问题暂时没有头绪

**Comment by EricDracula** [comment]
这个问题还没有解决吗？老版本也会这个问题吗？

**Comment by yanghaoxie** [comment]
好像在哪里看到说plasma最新的notification重写了，目前wine不支持。

**Comment by debugbb** [comment]
持续关注，目前还是没有通知

**Comment by EricDracula** [comment]
能不能像 TIM 那样呢？我记得好像 TIM 是作者维护的另一个repo，来了消息以后通知栏的图标会变成发消息的人的头像..

**Comment by SeanPcWoo** [comment]
现在问题有解决方法了吗？
我 archlinux + KDE 没有提示，只有声音，很难受
