### ISSUE TITLE
分享一个解决办法，关于公众号的文章在chrome打开后，无法听音频的问题

### ISSUE THREAD

**Issue by Brannua** [countstarlight/deepin-wine-wechat-arch#104]
- 个人环境：Manjaro20.2.1 + kde5.79.0，deepin-wine5，微信 3.1.0.72，公众号的文章直接在微信中是打不开的，显示为黑色背景；解决办法：
    1. 在微信的设置里进行设置“使用系统默认浏览器打开网页”，当然我的默认浏览器是yay安装的chrome stable版本；
    2. ok能打开文章了，但是音频无法播放，测试发现这是由于在 linux 环境中 chrome 的 UA 标识的问题，当我 f12 打开 console 控制台，然后在 network 中禁用 User agent 的自动选择，并将 user agent 改为 Microsoft Edge（EdgeHTML）--- Windows 后，保持控制台打开的状态下刷新网页，就可以正常播放 audio 音频了。

**Comment by JoveYu** [comment]
我之前内置浏览器一切正常可以正常访问网页的  最近几天也黑屏了不知道为什么
