### ISSUE TITLE
修改为 deepin-wine5 后无法设置 winecfg

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [countstarlight/deepin-wine-wechat-arch#105]
![image](https://user-images.githubusercontent.com/11333496/111056562-d3600180-84ba-11eb-909b-beb333fc2ccf.png)
由于字体很小，想要设置一下 wechat 里的字体，但是无法打开 winecfg

**Comment by countstarlight** [comment]
与 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/103 重复
