### ISSUE TITLE
希望默认把文泉驿微雅黑加入到wine环境里面

### ISSUE THREAD

**Issue by yswtrue** [countstarlight/deepin-wine-wechat-arch#109]
现在每更新一次版本，就需要重新复制字体进fonts目录比较麻烦，如果可以把文泉驿内嵌就很棒了，谢谢

**Comment by countstarlight** [comment]
因为原版安装包里已经自带了字体文件，就没有再链接 `wqy-microhei` 字体；之前也有人反映过这个问题，我会在下个版本把字体链接再加回去。

**Comment by zlianzhuang** [comment]
可以讲一下怎么复制么? 我的电脑上字体断断续续的,感觉像是字体的原因

**Comment by countstarlight** [comment]
`v3.2.1.151-1` 开始已经默认将 `wqy-microhei` 字体文件链接到 `WINEPREFIX` 环境
