### ISSUE TITLE
為什麼開啟後會有一個沒用的視窗？

### ISSUE THREAD

**Issue by laichiaheng** [countstarlight/deepin-wine-wechat-arch#11]
那個 chatcontactmenu 是作什麼用的？有時候還會多出第四個方框視窗
![2019-03-28 23-14-57 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/55169294-812f5400-51af-11e9-94e2-42c026d5fb73.png)

**Comment by countstarlight** [comment]
暂时不清楚，在kde平台上没有遇到

**Comment by kmvan** [comment]
gnome 你需要安装一个叫 tray 啥的插件，弄成系统托盘的。

**Comment by laichiaheng** [comment]
@kmvan 你是說 TopIcon? 我不是指那個 indicator，而是由個毫無作用的 chatcontactmenu 在那邊，而且關不掉

**Comment by laichiaheng** [comment]
這個黑色方框最影響使用，必須要多次重啟 WeChat 才有一定的機率消除他

**Comment by zhjcreator** [comment]
爬到了个不是解决方法的解决方法，群聊里打@之后再删除就好了。

**Comment by countstarlight** [comment]
这个问题在`v2.8.0.116-2`应该已经解决：https://github.com/countstarlight/deepin-wine-wechat-arch/issues/45
