### ISSUE TITLE
更新到3.2.1.127点击左侧任意联系人查看当前消息 应用直接卡死然后弹窗提示重启

### ISSUE THREAD

**Issue by meteoryun** [countstarlight/deepin-wine-wechat-arch#111]
系统manjaro 21,kde桌面环境，在更新微信到新版本之后，点击左侧列表中的任意一个联系人查看消息，应用直接卡住无响应，然后弹窗提示程序错误并重启.
![aa](https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=1177478917,2060405558&fm=26&gp=0.jpg)
![bb](https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=878711772,2993565776&fm=26&gp=0.jpg)

**Comment by countstarlight** [comment]
与 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/87 重复
