### ISSUE TITLE
WeChatSetup-3.2.1.151.exe hash failed

### ISSUE THREAD

**Issue by jackmin** [countstarlight/deepin-wine-wechat-arch#114]
==> Validating source files with md5sums...
    com.qq.weixin.deepin_2.9.5.41deepin7_i386.deb ... Passed
    WeChatSetup-3.2.1.151.exe ... FAILED
    run.sh ... Passed
==> ERROR: One or more files did not pass the validity check!

**Comment by countstarlight** [comment]
The download CDN you are connected to may be delayed. You can use the installation package to install: https://github.com/countstarlight/deepin-wine-wechat-arch/releases
