### ISSUE TITLE
WeChatSetup-3.2.1.151.exe md5校验不通过

### ISSUE THREAD

**Issue by shenhunluo** [countstarlight/deepin-wine-wechat-arch#116]
下载下来的 WeChatSetup-3.2.1.151.exe md5值是 ea0a150ac98d022e9c6054154f27ddb4

**Comment by countstarlight** [comment]
感谢提醒，已更新：https://github.com/countstarlight/deepin-wine-wechat-arch/commit/adcf0a14749eaf19e836e0d5d635fe1d034fcced
