### ISSUE TITLE
 错误： 一个或多个文件没有通过有效性检查！

### ISSUE THREAD

**Issue by starsareintherose** [countstarlight/deepin-wine-wechat-arch#117]
==> 获取源代码...
  -> 找到 com.qq.weixin.deepin_2.9.5.41deepin7_i386.deb
  -> 找到 WeChatSetup-3.2.1.151.exe
  -> 找到 run.sh
==> 正在验证 source 文件，使用md5sums...
    com.qq.weixin.deepin_2.9.5.41deepin7_i386.deb ... 通过
    WeChatSetup-3.2.1.151.exe ... 失败
    run.sh ... 通过
==> 错误： 一个或多个文件没有通过有效性检查！
下载源文件时出错: deepin-wine-wechat

**Comment by countstarlight** [comment]
与 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/116 重复
