### ISSUE TITLE
更新到3.3.0.93电脑端无法登陆，点击登陆之后手机上接收不到请求

### ISSUE THREAD

**Issue by meteoryun** [countstarlight/deepin-wine-wechat-arch#122]

**Comment by countstarlight** [comment]
再运行一次[自动切换](https://github.com/countstarlight/deepin-wine-wechat-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E6%8E%A8%E8%8D%90)试试？

**Comment by swimmingchar** [comment]
我的都不出现二维码了，感觉好像上不了网似的

**Comment by swimmingchar** [comment]
> 再运行一次[自动切换](https://github.com/countstarlight/deepin-wine-wechat-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E6%8E%A8%E8%8D%90)试试？

切换过了，不行。。。

**Comment by swimmingchar** [comment]
> 再运行一次[自动切换](https://github.com/countstarlight/deepin-wine-wechat-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E6%8E%A8%E8%8D%90)试试？

不是自动切换的问题，我的安装路径下只有一个deepin的wechat版本，安装的时候覆盖安装，感觉可能是wine的网络部分调用有问题。

**Comment by meteoryun** [comment]
我也觉得是，网络部分调用出问题了

**Comment by jackmin** [comment]
我也遇到了同样的问题。手机端收不到登录请求。需要收集哪些log吗？

**Comment by countstarlight** [comment]
archlinux + wine/deepin-wine 不能复现这个问题，尝试删除 `deepin-wine-wechat-arch` 本地安装目录：
```bash
rm -rf ~/.deepinwine/Deepin-WeChat
```
再启动：
```bash
/opt/apps/com.qq.weixin.deepin/files/run.sh -d #(可选)切换到 deepin-wine
/opt/apps/com.qq.weixin.deepin/files/run.sh 
```

**Comment by jackmin** [comment]
@countstarlight :+1: 的确切换到deepin-wine就可以登录了。多谢！

**Comment by zzhzero** [comment]
感觉是网络的问题，我删除账号信息以后登录二维码无法加载

**Comment by meteoryun** [comment]
切换到 deepin-wine的确可以了，谢谢
