### ISSUE TITLE
切换到deepin-wine6上

### ISSUE THREAD

**Issue by JoveYu** [countstarlight/deepin-wine-wechat-arch#125]
目前深度的包已经切换到deepin-wine6上了   可以考虑对接下

另外最近发现奇怪的事用这个包，可以正常使用内置浏览器打开网页，用咱这个就白屏
https://aur.archlinux.org/packages/com.qq.weixin.deepin/

**Comment by countstarlight** [comment]
`deepin-wine-wechat` 从 `v3.3.5.42` 开始，默认使用AUR仓库 [deepin-wine6-stable](https://aur.archlinux.org/packages/deepin-wine6-stable/)，不再依赖 `wine`
