### ISSUE TITLE
Manjaro KDE安装后启动报错

### ISSUE THREAD

**Issue by liyuj** [countstarlight/deepin-wine-wechat-arch#130]
安装方式：
yay -S deepin-wine-wechat
然后点击图标启动后报错，详细信息如下：
Unhandled exception: page fault on read access to 0x0c1aba08 in 32-bit code (0x6870abe9).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:6870abe9 ESP:0021ebe0 EBP:0021ec48 EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:00610074 EBX:0c1aba00 ECX:0021ec48 EDX:00000000
 ESI:00000000 EDI:7b60e028
Stack dump:
0x0021ebe0:  00000000 0021ec00 0021ec98 0021ec10
0x0021ebf0:  00303ba0 7b6322b0 0021ec98 7b60e028
0x0021ec00:  6ca812c0 24040065 00000202 6871628c
0x0021ec10:  70bcacc0 00000000 00000000 6870cb9d
0x0021ec20:  68716280 0000003b 00000000 00000000
0x0021ec30:  00000000 00000000 00000000 00000000
Backtrace:
=>0 0x6870abe9 EntryPoint+0xffffffff() in uxtheme (0x0021ec48)
  1 0x6870cb9d EntryPoint+0xffffffff() in uxtheme (0x00000000)
  2 0x68710653 EntryPoint+0xffffffff() in uxtheme (0x0021f128)
  3 0x6871075a EntryPoint+0xffffffff() in uxtheme (0x0021f158)
  4 0x687029c2 EntryPoint+0xffffffff() in uxtheme (0x0021f208)
  5 0x6ed269eb EntryPoint+0xffffffff() in user32 (0x0021f248)
  6 0x6edac84c EntryPoint+0xffffffff() in user32 (0x0021f288)
  7 0x6edad017 EntryPoint+0xffffffff() in user32 (0x0000031a)
  8 0x6edaf693 EntryPoint+0xffffffff() in user32 (0x6edb8638)
  9 0x6ed5fa31 EntryPoint+0xffffffff() in user32 (0x00000000)
  10 0x6ed652cc EntryPoint+0xffffffff() in user32 (0x00000001)
  11 0x6ed65524 EntryPoint+0xffffffff() in user32 (0x0021f468)
  12 0x68710896 EntryPoint+0xffffffff() in uxtheme (0x0021f4b8)
  13 0x68702a25 EntryPoint+0xffffffff() in uxtheme (0x0021f568)
  14 0x6ed269eb EntryPoint+0xffffffff() in user32 (0x0021f5a8)
  15 0x6edac84c EntryPoint+0xffffffff() in user32 (0x0021f5e8)
  16 0x6edad017 EntryPoint+0xffffffff() in user32 (0x00000002)
  17 0x6edaf693 EntryPoint+0xffffffff() in user32 (0x6edb8638)
  18 0x6ed5fa31 EntryPoint+0xffffffff() in user32 (0x00000000)
  19 0x6ed652cc EntryPoint+0xffffffff() in user32 (0x00000001)
  20 0x6ed65524 EntryPoint+0xffffffff() in user32 (0x0021f7c8)
  21 0x6ed9d3d0 EntryPoint+0xffffffff() in user32 (0x0021f868)
  22 0x6ed9f707 EntryPoint+0xffffffff() in user32 (0x0021f868)
  23 0x00402d3b EntryPoint+0xffffffff() in wechatsetup-3.3.0.115 (0x0021f8fc)
  24 0x004032ee EntryPoint+0xffffffff() in wechatsetup-3.3.0.115 (0x0040be90)
0x6870abe9 EntryPoint+0xffffffff in uxtheme: cmpw	$0,0x8(%ebx)
Modules:
Module	Address			Debug info	Name (23 modules)
PE	  400000-  467000	Export          wechatsetup-3.3.0.115
PE	  470000-  5d3000	Deferred        comctl32
PE	10000000-10006000	Deferred        system
PE	61740000-61782000	Deferred        advapi32
PE	62fc0000-6304f000	Deferred        rpcrt4
PE	63480000-6348c000	Deferred        version
PE	63bc0000-63bd9000	Deferred        shcore
PE	64a40000-64a95000	Deferred        shlwapi
PE	68500000-6855b000	Deferred        combase
PE	68700000-6872f000	Dwarf           uxtheme
PE	6a400000-6a531000	Deferred        ole32
PE	6bc00000-6bc2a000	Deferred        sechost
PE	6bcc0000-6bd40000	Deferred        setupapi
PE	6c9c0000-6cc53000	Deferred        gdi32
PE	6d300000-6d308000	Deferred        shfolder
PE	6ed00000-6ef24000	Dwarf           user32
PE	70b40000-70c1f000	Deferred        ucrtbase
PE	71200000-7121b000	Deferred        imm32
PE	7b000000-7b0e8000	Deferred        kernelbase
PE	7b600000-7b81b000	Deferred        kernel32
PE	7bc00000-7bc9c000	Deferred        ntdll
PE	7d940000-7d944000	Deferred        winex11
PE	7dfc0000-7e897000	Deferred        shell32
Threads:
process  tid      prio (all id:s are in hex)
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	00000068    0
	00000080    0
	000000a4    0
	000000e4    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	0000005c    0
00000060 plugplay.exe
	00000064    0
	0000006c    0
	00000070    0
	00000074    0
	0000008c    0
00000078 winedevice.exe
	0000007c    0
	00000084    0
	00000088    0
	00000094    0
	00000098    0
0000009c svchost.exe
	000000a0    0
	000000a8    0
	000000ac    0
000000b8 explorer.exe
	000000bc    0
	000000d0    0
	000000d4    0
000000dc rpcss.exe
	000000e0    0
	000000ec    0
	000000f0    0
	000000f4    0
	000000f8    0
	000000fc    0
00000138 (D) C:\Program Files\Tencent\WeChatSetup-3.3.0.115.exe
	0000013c    0 <==
	00000148    0
System information:
    Wine build: wine-6.13
    Platform: i386
    Version: Windows 7
    Host system: Linux
    Host version: 5.13.5-1-MANJARO

**Comment by countstarlight** [comment]
用[自动切换](https://github.com/countstarlight/deepin-wine-wechat-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E6%8E%A8%E8%8D%90)切换到 `deepin-wine` 试试

**Comment by liyuj** [comment]
切换到deepin-wine也不行。
卸载后，用yay -S com.qq.weixin.deepin安装这个包就可以。

**Comment by its404** [comment]
我也遇到一样的问题，但这个问题只出现在我的AMD CPU的机器上，我有另外一台Intel CPU的机器，可以正常安装运行这个版本。
