### ISSUE TITLE
无法打开群聊成员

### ISSUE THREAD

**Issue by Alvintan0712** [countstarlight/deepin-wine-wechat-arch#132]
如标题

**Comment by countstarlight** [comment]
用[自动切换](https://github.com/countstarlight/deepin-wine-wechat-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E6%8E%A8%E8%8D%90)切换到 `deepin-wine` 试试

**Comment by Alvintan0712** [comment]
可以了，谢谢
