### ISSUE TITLE
 WeChatSetup-3.3.5.34.exe MD5校验错误

### ISSUE THREAD

**Issue by bin9853** [countstarlight/deepin-wine-wechat-arch#135]

**Comment by tracy1989wan** [comment]
me too!!!

**Comment by countstarlight** [comment]
已更新：https://github.com/countstarlight/deepin-wine-wechat-arch/commit/120d2dedd5dd9d018a14e8ff832f34fe2fcc57a3

**Comment by its404** [comment]
还是md5校验错误，`WeChatSetup-3.3.5.42.exe`的md5应该是`b00096cd430a6e32c65e4fa98312599b`。

**Comment by countstarlight** [comment]
@its404 `b00096cd430a6e32c65e4fa98312599b` 是上一个版本(`3.3.5.34`)的 md5值，应该是你连接的服务器缓存导致，可以过段时间再试或[用安装包安装](https://github.com/countstarlight/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

**Comment by its404** [comment]
@countstarlight 应该是缓存问题，安装包安装成功了。谢谢！
