### ISSUE TITLE
无法下载 https://community-packages.deepin.com/deepin/pool/non-free/u/udis86/udis86_1.72-2_i386.deb

### ISSUE THREAD

**Issue by SShnoodles** [countstarlight/deepin-wine-wechat-arch#136]
如题

**Comment by countstarlight** [comment]
这是个什么？`deepin-wine-wechat` 打包过程中不需要下载这个

**Comment by SShnoodles** [comment]
哦，我搞错了

**Comment by SShnoodles** [comment]
切换到 deepin-wine 的时候会执行次下载

**Comment by countstarlight** [comment]
`deepin-wine-wechat` 是最新版吗，执行的切换命令是否为：
```bash
/opt/apps/com.qq.weixin.deepin/files/run.sh -d
```

**Comment by SShnoodles** [comment]
> `deepin-wine-wechat` 是最新版吗，执行的切换命令是否为：
> 
> ```shell
> /opt/apps/com.qq.weixin.deepin/files/run.sh -d
> ```

是最新版的

**Comment by alvin0173** [comment]
同样问题
>   -> 正在下载 udis86_1.72-2_i386.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> 错误： 无法下载 https://community-packages.deepin.com/deepin/pool/non-free/u/udis86/udis86_1.72-2_i386.deb
    正在放弃...
下载源文件时出错: deepin-udis86

**Comment by countstarlight** [comment]
安装 `deepin-udis86` 失败是因为 aur仓库 [deepin-udis86](https://aur.archlinux.org/packages/deepin-udis86/) 需要更新，[archlinuxcn](https://mirror.tuna.tsinghua.edu.cn/help/archlinuxcn/)源里有打包好的[deepin-udis86-1.72_2-3-x86_64.pkg.tar.xz](https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/x86_64/deepin-udis86-1.72_2-3-x86_64.pkg.tar.xz)，可以下载安装包或从源里安装

**Comment by syvshc** [comment]
> 安装 `deepin-udis86` 失败是因为 aur仓库 [deepin-udis86](https://aur.archlinux.org/packages/deepin-udis86/) 需要更新，[archlinuxcn](https://mirror.tuna.tsinghua.edu.cn/help/archlinuxcn/)源里有打包好的[deepin-udis86-1.72_2-3-x86_64.pkg.tar.xz](https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/x86_64/deepin-udis86-1.72_2-3-x86_64.pkg.tar.xz)，可以下载安装包或从源里安装

链接失效

**Comment by linguishi** [comment]
同出现该error，大佬们该怎么搞？

**Comment by syvshc** [comment]
> 同出现该error，大佬们该怎么搞？

有人打包了新的 `deepin-udis86`, repo 在这里 https://github.com/JohnMasoner/deepin-udis86 , 先安装 `deepin-udis86`, 再安装 `deepin-wine-wechat`
