### ISSUE TITLE
為什麼有兩個 WeChat 圖示？

### ISSUE THREAD

**Issue by laichiaheng** [countstarlight/deepin-wine-wechat-arch#14]
![2019-04-04 13-05-58 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/55530860-6b9fba00-56da-11e9-8966-222ef82458ab.png)

**Comment by countstarlight** [comment]
其中一个应该是在运行微信安装程序时由安装程序创建的快捷方式

**Comment by kmvan** [comment]
对，一个是exe生成的。

**Comment by kmvan** [comment]
![image](https://user-images.githubusercontent.com/3839554/55603542-bdf5df00-579d-11e9-9c72-7bd9fe9596d0.png)
我表示已经对exe生成的东西无所谓了，xfce会给他一个专用的wine程序组，里面的东西不看就行

**Comment by countstarlight** [comment]
@laichiaheng 已经提交更新，本地测试不会再创建第二个图标，卸载从AUR安装试试。

**Comment by laichiaheng** [comment]
@countstarlight 了解，感謝
