### ISSUE TITLE
更新一下md5sum？

### ISSUE THREAD

**Issue by hedonihilist** [countstarlight/deepin-wine-wechat-arch#141]
==> Validating source files with md5sums...
    com.qq.weixin.deepin_3.2.1.154deepin13_i386.deb ... Passed
    WeChatSetup-3.3.5.50.exe ... FAILED
    run.sh ... Passed
    reg.patch ... Passed

**Comment by countstarlight** [comment]
md5值已经更新到最新了(v3.3.5.50)，你的md5值是多少？

**Comment by hedonihilist** [comment]
我的是这：

```
❯ md5sum WeChatSetup-3.3.5.50.exe 
4204a40f3b9f4123c5347365a453473e  WeChatSetup-3.3.5.50.exe
```

**Comment by hedonihilist** [comment]
清了缓存，现在搞定了，md5正确，谢了
