### ISSUE TITLE
构建报错udis86_1.72-2_i386.deb 404 not found

### ISSUE THREAD

**Issue by wzyj1731** [countstarlight/deepin-wine-wechat-arch#143]
正在构建 deepin-udis86...
==> 正在创建软件包：deepin-udis86 1.72_2-3 (2021年09月05日 星期日 09时44分38秒)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系
==> 获取源代码...
  -> 正在下载 udis86_1.72-2_i386.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   146    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> 错误： 无法下载 https://community-packages.deepin.com/deepin/pool/non-free/u/udis86/udis86_1.72-2_i386.deb
    正在放弃...
构建 deepin-udis86 失败

**Comment by countstarlight** [comment]
与 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/136 重复
