### ISSUE TITLE
当微信不在最前端的时候会出现个白框，最小化几次莫名就解决了。还有两个图标是否有解决办法

### ISSUE THREAD

**Issue by ieiu** [countstarlight/deepin-wine-wechat-arch#15]
![深度截图_选择区域_20190405210730](https://user-images.githubusercontent.com/24524065/55629901-f8379e80-57e6-11e9-87fc-6a48e35b391e.png)
我使用的是majaro gnome
如图所示，每次启动都会这样，貌似看到前面也有人提过。
最小化再点出来重复几次，莫名的就消失了，不知道为啥。
还有请问前面issue的两个图标的问题是否有办法解决，我用的tim没有这个问题

**Comment by countstarlight** [comment]
在其他应用上方显示边框的问题，在wine bug提交平台很早前就被人提出来，一直没有进展，短期内应该不会解决。

**Comment by countstarlight** [comment]
@ieiu 已经提交更新，本地测试不会再创建第二个图标，卸载从AUR安装试试。

**Comment by ieiu** [comment]
> @ieiu 已经提交更新，本地测试不会再创建第二个图标，卸载从AUR安装试试。
> 移除之前在菜单创建的快捷方式使用：
> 
> ```shell
> rm -r ~/.local/share/applications/wine/Programs/WeChat
> ```

解决了，感谢！

**Comment by ieiu** [comment]
> @ieiu 已经提交更新，本地测试不会再创建第二个图标，卸载从AUR安装试试。
> 移除之前在菜单创建的快捷方式使用：
> 
> ```shell
> rm -r ~/.local/share/applications/wine/Programs/WeChat
> ```

昨天重装后好了，今天不知道为什么又出现了，重装了几次还是这样，
~/.local/share/applications/wine/Programs/下没有WeChat文件夹存在，
看了一下应该是最新的，run.sh中有env WINEDLLOVERRIDES="winemenubuilder.exe=d" WINEPREFIX="$WINEPREFIX" $WINE_CMD $APPDIR/$WECHAT_INSTALLER.exe这句话

**Comment by ieiu** [comment]
@countstarlight 抱歉没说明白，我指的是多出来一个叫做ChatContaceMenu的窗口，不是说多了一个启动图标

**Comment by ieiu** [comment]
这个pkgbuild是用的zip的安装包，里面的网址过期了，我在网上找了一个最新绿色版的替换了进去，构建出来的包安装后启动了几次试试，看起来没有白边的问题，供参考
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=deepin-wechat
我改之后的如下
# Maintainer: Ding Xiao <tinocodfcdsa10@mails.tsinghua.edu.cn>
# Maintainer: Jingbei Li <i@jingbei.li>
# Maintainer: Alia Skywol <skywol@qq.com>

pkgname=deepin-wechat
pkgver=2.6.4.38
pkgrel=4
pkgdesc="Tencent WeChat Client on Deepin Wine Updated"
arch=("x86_64")
url="http://www.deepin.com/"
license=('custom')
depends=('wine' 'lib32-libldap' 'p7zip' 'xdotool' 'xorg-xwininfo' 'deepin-wine')
makedepends=('unzip' 'tar')
optdepends=('noto-fonts-cjk: Chinese fonts that wine recognizes (you can use other fonts, but you will have to configure manually on winecfg)'
	    'gnome-shell-extension-topicons-plus-huttli-git: Show tray icon on topbar on gnome instead of wine floating window')

_mirror="https://mirrors.tuna.tsinghua.edu.cn/deepin"
source=("$_mirror/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.2.31deepin0_i386.deb" "http://8dx.pc6.com/xjq6/WeChat_v2.6.7.57.zip")
sha1sums=('8e427de964b83c642ff51f180ad161c3d754ca36' 'e01a344e5f38581b8aba2abe7d9f46aaed81a4cf')

package() {
  cd ${srcdir}
  #1) Install deepin-wine wechat!
  tar -xvf data.tar.xz -C ${pkgdir}

  #2) Install update version with latest wechat (it'd be awesome if I could figure out how to get this in a more human readable format for next update:) )
  unzip 'WeChat_v2.6.7.57.zip' -d update
  cp ${pkgdir}/opt/deepinwine/apps/Deepin-WeChat/files.7z ./
  7za x files.7z -ofiles
  cp -r update/WeChat2.6.7.57/* 'files/drive_c/Program Files/Tencent/WeChat/'
  cd files
  7za a files.7z
  cd ..
  cp files/files.7z "${pkgdir}"/opt/deepinwine/apps/Deepin-WeChat/files.7z

  #3) Fix deepin-wine language to correctly print CJK characters
  cd ${pkgdir}
  chmod -x usr/share/applications/deepin.com.wechat.desktop
  sed '30a\sed -i "s/deepin-wine/LANG=zh_CN.UTF-8 wine/" $1/drive_c/deepin/EnvInit.sh' -i opt/deepinwine/apps/Deepin-WeChat/run.sh
  
}

**Comment by Kryptia** [comment]
> 在其他应用上方显示边框的问题，在wine bug提交平台很早前就被人提出来，一直没有进展，短期内应该不会解决。

请问有相关patch吗？

**Comment by countstarlight** [comment]
@maghsk 问题在 [163music / WeChat: shadow of windows is always on the top of desktop](https://bugs.winehq.org/show_bug.cgi?id=34631)，有hack，但是没有效果

**Comment by countstarlight** [comment]
@ieiu 感谢你的帮助，我会试试能不能解决

**Comment by feileb** [comment]
wine有这个问题，deepin-wine是好的
修改下面两个文件：
/opt/deepinwine/tools/run.sh 
/opt/deepinwine/apps/Deepin-WeChat/run.sh
将WINE_CMD改为deepin-wine
上面的方法可以解决这个问题，但是deepin-wine的字体渲染会发虚。

**Comment by zidoshare** [comment]
> @countstarlight 抱歉没说明白，我指的是多出来一个叫做ChatContactMenu的窗口，不是说多了一个启动图标

archlinux 下，还是有两个图标，除了微信的图标外，还有一个非常小的[ChatContactMenu]图标，不知道是干什么的，并且也不知道怎么解决，


> @ieiu 已经提交更新，本地测试不会再创建第二个图标，卸载从AUR安装试试。
> 移除之前在菜单创建的快捷方式使用：
> 
> ```shell
> rm -r ~/.local/share/applications/wine/Programs/WeChat
> ```

并没有`~/.local/share/applications/wine/Programs/WeChat`这个目录

**Comment by ieiu** [comment]
@zidoshare 
我也有那个ChatContactMenu窗口，没找到办法解决，也不影响使用，就没管了
那个回复中的图标不是这个问题，是指启动图标

**Comment by violetbobo** [comment]
> wine有这个问题，deepin-wine是好的
> 修改下面两个文件：
> /opt/deepinwine/tools/run.sh
> /opt/deepinwine/apps/Deepin-WeChat/run.sh
> 将WINE_CMD改为deepin-wine
> 上面的方法可以解决这个问题，但是deepin-wine的字体渲染会发虚。

安装`lib32-freetype2-infinality-ultimate`后就不发虚了

**Comment by zidoshare** [comment]
> > wine有这个问题，deepin-wine是好的
> > 修改下面两个文件：
> > /opt/deepinwine/tools/run.sh
> > /opt/deepinwine/apps/Deepin-WeChat/run.sh
> > 将WINE_CMD改为deepin-wine
> > 上面的方法可以解决这个问题，但是deepin-wine的字体渲染会发虚。
> 
> 安装`lib32-freetype2-infinality-ultimate`后就不发虚了

哇！真的好了，非常非常非常感谢，帮大忙了！

**Comment by adra2n** [comment]
改成deepin-wine 无法启动是怎么回事，求帮忙啊

**Comment by debugbb** [comment]
@adra2n  deepin-wine需要安装gnome-settings-daemon,并设置自动启动

**Comment by adra2n** [comment]
@debugbb 本身就是gnome也自动启动了，但是改成deepin-wine后还是无法启动，改成wine是没问题的

**Comment by zhjcreator** [comment]
> @countstarlight 抱歉没说明白，我指的是多出来一个叫做ChatContactMenu的窗口，不是说多了一个启动图标

爬到了个不是解决方法的解决方法，群聊里打@之后再删除就好了。

**Comment by wwangbzh** [comment]
> wine有这个问题，deepin-wine是好的
> 修改下面两个文件：
> /opt/deepinwine/tools/run.sh
> /opt/deepinwine/apps/Deepin-WeChat/run.sh
> 将WINE_CMD改为deepin-wine
> 上面的方法可以解决这个问题，但是deepin-wine的字体渲染


> @adra2n deepin-wine需要安装gnome-settings-daemon,并设置自动启动

1、xfce安装gnome-settings-daemon 不能设置为自启动，自启动提示警告：
(gsd-xsettings:2847): xsettings-plugin-WARNING **: 12:25:42.378: You can only run one xsettings manager at a time; exiting Failed to start: Could not initialize xsettings manager.
所有说xfce环境切换deepin-wine是失败的，
2、使用自动切换命令后，只有安装完成后第一次打开成功，关机重启后就无法打开了，

**Comment by debugbb** [comment]
@wwangbzh 关于第二个问题，你是不是安装的时候修改了安装路径，如果是的话，需要改一下run.sh
如果更换了安装路径，请复制一下安装界面中识别出来的路径，然后一定记着去run.sh中把以下更换成更换后的路径（大约在32行）：
env WINEPREFIX="$WINEPREFIX" WINEDEBUG=-msvcrt $WINE_CMD "Z:\home\xxx\apps\wechat\WeChat.exe" &

**Comment by wwangbzh** [comment]
> @wwangbzh 关于第二个问题，你是不是安装的时候修改了安装路径，如果是的话，需要改一下run.sh
> 如果更换了安装路径，请复制一下安装界面中识别出来的路径，然后一定记着去run.sh中把以下更换成更换后的路径（大约在32行）：
> env WINEPREFIX="$WINEPREFIX" WINEDEBUG=-msvcrt $WINE_CMD "Z:\home\xxx\apps\wechat\WeChat.exe" &

没有路径，也没有配置，全部都是默认。

**Comment by hanxi** [comment]
找到这个解决方案，虽然奇葩，但是有效。
https://manateelazycat.github.io/linux/2019/09/29/wechat-transparent-window.html

**Comment by countstarlight** [comment]
@hanxi 感谢帮助，找到一个cpp实现的版本，参照[#消除阴影边框](https://github.com/countstarlight/deepin-wine-wechat-arch#%E6%B6%88%E9%99%A4%E9%98%B4%E5%BD%B1%E8%BE%B9%E6%A1%86)解决

**Comment by ijackwu** [comment]
> > @countstarlight 抱歉没说明白，我指的是多出来一个叫做ChatContactMenu的窗口，不是说多了一个启动图标
> 
> 爬到了个不是解决方法的解决方法，群聊里打@之后再删除就好了。

哈~解决

**Comment by wwangbzh** [comment]
您好  邮件已经收到，如果问题会尽快反馈。
