### ISSUE TITLE
请问安装微信时，没安装那个.net mono有问题吗？

### ISSUE THREAD

**Issue by loogimvar** [countstarlight/deepin-wine-wechat-arch#18]
你好，我安装微信的时候，取消安装.net mono了。请问对日后有影响吗？我现在用着也没发现有什么问题，很好。谢谢！

**Comment by loogimvar** [comment]
解决了，我是菜鸟，原来是我没开启Multilib仓库，都怪我没仔细看说明，不好意思。太好了，又可以用微信，对我来说已经好完美了，谢谢大神啊。

**Comment by kmvan** [comment]
貌似不影响

**Comment by countstarlight** [comment]
没有影响，mono应该已经作为依赖安装了，不知道为什么还会出现那个对话框
