### ISSUE TITLE
无法安装微信

### ISSUE THREAD

**Issue by logTXT** [countstarlight/deepin-wine-wechat-arch#20]
出错部分：
==> 正在验证 source 文件，使用md5sums...
    deepin.com.wechat_2.6.2.31deepin0_i386.deb ... 通过
    WeChat_C1022.exe ... 失败
    run.sh ... 通过
    reg.patch ... 通过
==> 错误： 一个或多个文件没有通过有效性检查！
Error downloading sources: deepin-wine-wechat
系统环境：manjaro+KDE

**Comment by loogimvar** [comment]
手动安装就可以了。
 git clone https://github.com/countstarlight/deepin-wine-wechat-arch.git

 cd deepin-wine-wechat-arch
  
 makepkg -si

**Comment by logTXT** [comment]
好的，我晚上再试一下

**Comment by countstarlight** [comment]
@logTXT 也可以从github release里下载打包好的安装包直接安装: [从 GitHub Release 安装](https://github.com/countstarlight/deepin-wine-wechat-arch#%E4%BB%8E-github-release-%E5%AE%89%E8%A3%85)

**Comment by countstarlight** [comment]
https://github.com/countstarlight/deepin-wine-wechat-arch/commit/81492c3b46e62ac03d7673b667d85aca311df9ad

**Comment by git197** [comment]
> 出错部分：
> ==> 正在验证 source 文件，使用md5sums...
> deepin.com.wechat_2.6.2.31deepin0_i386.deb ... 通过
> WeChat_C1022.exe ... 失败
> run.sh ... 通过
> reg.patch ... 通过
> ==> 错误： 一个或多个文件没有通过有效性检查！
> Error downloading sources: deepin-wine-wechat
> 系统环境：manjaro+KDE

我的还是不可以啊  还是这个错误

**Comment by countstarlight** [comment]
@git197 看你的提示，应该用的不是最新的源码，可以更新后再打包:
```bash
cd deepin-wine-wechat-arch
./gen.sh -c
git pull
makepkg -si
```
或者直接用打包好的安装包安装: [用安装包安装](https://github.com/countstarlight/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

**Comment by logTXT** [comment]
> > 出错部分：
> > ==> 正在验证 source 文件，使用md5sums...
> > deepin.com.wechat_2.6.2.31deepin0_i386.deb ... 通过
> > WeChat_C1022.exe ... 失败
> > run.sh ... 通过
> > reg.patch ... 通过
> > ==> 错误： 一个或多个文件没有通过有效性检查！
> > Error downloading sources: deepin-wine-wechat
> > 系统环境：manjaro+KDE
> 
> 我的还是不可以啊 还是这个错误

这种情况一般是下载的文件有小版本更新，sha计算值变了，可以在缓存的PKGBUILD里面改一下对应文件的sha256sums，然后在有PKGBUILD的文件下手动安装，就OK

**Comment by catinred2** [comment]
运行一下  `updpkgsums`  命令即可
