### ISSUE TITLE
当前系统是32位，无法安装64位的应用

### ISSUE THREAD

**Issue by ghost** [countstarlight/deepin-wine-wechat-arch#292]
![image](https://github.com/vufa/deepin-wine-wechat-arch/assets/121380747/7462671a-e510-416b-887c-96f3a5737d78)
初次运行出错，请问该如何解决？

**Comment by yangchengwork** [comment]
请教您是如何解决的，我现在电脑也有这个问题

**Comment by Seraphli** [comment]
我也有同样的问题，可能是环境不干净导致的，怎么解决

**Comment by yangchengwork** [comment]
> 我也有同样的问题，可能是环境不干净导致的，怎么解决

参考https://aur.archlinux.org/packages/deepin-wine-wechat上的问题，下载https://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.9.0.28上的exe文件，这时MD5SUM是对的，安装后就没有问题。而不要使用官网上下载的exe

**Comment by Seraphli** [comment]
> > 我也有同样的问题，可能是环境不干净导致的，怎么解决
> 
> 参考[https://aur.archlinux.org/packages/deepin-wine-wechat上的问题，下载https://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.9.0.28上的exe文件，这时MD5SUM是对的，安装后就没有问题。而不要使用官网上下载的exe](https://aur.archlinux.org/packages/deepin-wine-wechat%E4%B8%8A%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E4%B8%8B%E8%BD%BDhttps://github.com/tom-snow/wechat-windows-versions/releases/tag/v3.9.0.28%E4%B8%8A%E7%9A%84exe%E6%96%87%E4%BB%B6%EF%BC%8C%E8%BF%99%E6%97%B6MD5SUM%E6%98%AF%E5%AF%B9%E7%9A%84%EF%BC%8C%E5%AE%89%E8%A3%85%E5%90%8E%E5%B0%B1%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98%E3%80%82%E8%80%8C%E4%B8%8D%E8%A6%81%E4%BD%BF%E7%94%A8%E5%AE%98%E7%BD%91%E4%B8%8A%E4%B8%8B%E8%BD%BD%E7%9A%84exe)

这个跟md5校验没关系吧，这个是wine32但是安装包是64的问题吧

**Comment by poppy473** [comment]
请问解决了吗？

**Comment by Seraphli** [comment]
@poppy473 解决了，参考这条评论，完全重复这条评论的步骤
![image](https://github.com/vufa/deepin-wine-wechat-arch/assets/1586755/e473df76-8d71-4f53-ad8c-ab62f479ea1d)
