### ISSUE TITLE
更新后微信输入法切换不了中文了

### ISSUE THREAD

**Issue by GitHublilei** [countstarlight/deepin-wine-wechat-arch#31]
不过,TIM可以输入中文

**Comment by sduqlsc** [comment]
同问题，deepin-wine-wechat  2.6.8.65-1，输入法不能切换，TIM正常。

**Comment by liangjiezhu** [comment]
same error

**Comment by ystyle** [comment]
同样的问题....

**Comment by GitHublilei** [comment]
我这边自己已经解决了，发现是wine 4.17-1的问题，手动降级成4.16-1就可以了

**Comment by sduqlsc** [comment]
@GitHublilei   感谢，降级成功
```
wget https://archive.archlinux.org/packages/w/wine/wine-4.16-1-x86_64.pkg.tar.xz

sudo pacman -U wine-4.16-1-x86_64.pkg.tar.xz
```

然后重启微信后正常。

**Comment by liangjiezhu** [comment]
@GitHublilei  
@sduqlsc  
感谢,可以了~~

**Comment by countstarlight** [comment]
是wine 4.17的一个 bug：[bug #47821](https://bugs.winehq.org/show_bug.cgi?id=47821)，已经有相应的修复补丁：[patch for bug #47821](https://bugs.winehq.org/attachment.cgi?id=65352&action=diff)，等待解决

**Comment by xhw20190116** [comment]
试试这个，sudo pacman --noconfirm -U /var/cache/pacman/pkg/wine-4.15-1-x86_64.pkg.tar.xz

**Comment by time-and-fate** [comment]
wine 4.19 修复这个问题了，可以升级了

**Comment by countstarlight** [comment]
wine 4.19已经修复

**Comment by sduqlsc** [comment]
补充说明：2019年12月06日

目前Manjaro的版本在4.18，所以需要手动升级到4.20：

```
wget http://mirror.ubrco.de/archlinux/multilib/os/x86_64/wine-4.21-1-x86_64.pkg.tar.xz
```

**Comment by liealis** [comment]
我先把wine降级到4.19版本还是 不能解决问题。无法切换输入法。

目前状况——————
微信版本是3.0.0.57
切换到了deepin-wine
