### ISSUE TITLE
可以通过设置Wine的Windows版本为Win7解决公众号文章或小程序打开后崩溃的问题

### ISSUE THREAD

**Issue by sherpahu** [countstarlight/deepin-wine-wechat-arch#35]
当Wine的Windows版本设置为Win10时会出现公众号文章打开崩溃，小程序使用一段时间也崩溃的问题。
但我发现通过`WINEPREFIX=~/.deepinwine/Deepin-WeChat /usr/bin/wine winecfg`设置应用程序中的Windows版本为Windows7后可以正常查看公众号的文章，也可以打开小程序而不崩溃。
我的环境：Manjaro 18.1.2 deepin-wine-wechat 2.7.1.88-1 （其中升级wine为4.20版本）
我解决了的问题：
1. 无法使用fcitx中文输入法（在[AUR](http://archlinux.thaller.ws/multilib/os/x86_64/wine-staging-4.20-1-x86_64.pkg.tar.xz)上下载Wine4.20然后通过`sudo pacman -U wine-staging-4.20-1-x86_64.pkg.tar.xz`[更新Wine到4.20解决](https://bugs.winehq.org/show_bug.cgi?id=47821)）
2. 登录时提示程序未被识别（这个问题不影响使用只影响心情2333），打开公众号文章后崩溃，打开小程序后崩溃，通过`WINEPREFIX=~/.deepinwine/Deepin-WeChat /usr/bin/wine winecfg`设置Windows版本为Windows 7后问题解决。如果设置为Windows XP可以解决公众号文章看不了的问题，但是无法使用小程序（微信不支持XP使用小程序）。至于说通过设置公众号文章在浏览器打开也可以正常看，但是无法查看公众号历史消息（需要诡异的验证）。

放两张截图
公众号没啥问题
![image](https://user-images.githubusercontent.com/30852287/69487907-6677c100-0e9d-11ea-9038-81dab2fc0692.png)
小程序也OK（扫描全能王挺好用的）
![image](https://user-images.githubusercontent.com/30852287/69487918-b5255b00-0e9d-11ea-9c62-6a2855b13409.png)
设置Windows版本是自己瞎折腾出来的，目前用着没什么问题，我在别的issue或者博客里没看到所以发上来（可能已经有人这么干了只不过我没看见，网页版刚被封使用Wine版微信的时间不长还请见谅，如果是重复的issue我马上删）。
最后，感谢打包wine微信的大佬！

**Comment by sherpahu** [comment]
但目前还发现微信里打开图片右键选择复制好像复制不了

**Comment by countstarlight** [comment]
感谢反馈， `deepin-wine-wechat` 从 2.7.1.82-2 开始，为解决崩溃问题，已经将wine设置为windows7版本：https://github.com/countstarlight/deepin-wine-wechat-arch/commit/f41080f71d245253c85e799c23feb0bbc799cd4d
公众号在win7上不会崩溃，但是是白屏，看来在xp上可以看

**Comment by EricDracula** [comment]
> 之前一直正常，版本为windows7 最近不知道为什么 小程序正常，内置浏览器白屏

有啥解决方法吗？

**Comment by EricDracula** [comment]
> 用浏览器打开吧，我只探索出来这样可以勉强用

hhh，其实早期我也这么用的，但是我记得之前有个版本更新后公众号可以看了。最近换了台电脑，装了最新的 deepin-wine-wechat 才发现公众号又看不了了。。

**Comment by JoveYu** [comment]
用AUR包com.qq.weixin.deepin    一切功能正常   包括截图   内置浏览器

**Comment by EricDracula** [comment]
> 用AUR包com.qq.weixin.deepin 一切功能正常 包括截图 内置浏览器

但是这个好像不能看朋友圈了又...

**Comment by JoveYu** [comment]
> 

朋友圈是新版本才有的功能，新一点的版本wine运行各种毛病，这个看你取舍吧，居然真的人有在电脑上刷朋友圈
