### ISSUE TITLE
KDE字体发虚

### ISSUE THREAD

**Issue by woqulegenicheng** [countstarlight/deepin-wine-wechat-arch#36]
在KDE上安装了lib32-freetype2-infinality-ultimate后，字体发虚仍然没有解决，deepin桌面下则解决了，貌似这个在KDE上不起作用

**Comment by nshusr** [comment]
我也一样的，不知道怎么解决

**Comment by feileb** [comment]
我的KDE，之前也是发虚，今天改了下字体配置发现好了
系统设置->字体
打开抗锯齿
子像素渲染：RGB
微调：完全

**Comment by xinghe98** [comment]
> 我的KDE，之前也是发虚，今天改了下字体配置发现好了
> 系统设置->字体
> 打开抗锯齿
> 子像素渲染：RGB
> 微调：完全
> 
> My KDE, which was also a blur, changed the font configuration today and found a good system setting -- font, open anti aliasing, Subpixel rendering: RGB FINE TUNING: complete

这样确实可以，但不知道为什么我每次重启/注销后需要重新应用一次

**Comment by Face-Smile** [comment]
@xinghe98 
`gnome-settings-daemon` 会破坏kde的字体设置，可以使用`xsettingsd`替代(包很小，依赖也少）
配置`xsettingsd`可以参考：https://github.com/derat/xsettingsd/wiki/Installation
配置文件默认在以下位置或者 `-c` 参数指定：
```
xsettingsd: Couldn't find config file. Tried the following:
  ~/.xsettingsd
  ~/.config/xsettingsd/xsettingsd.conf
  /etc/xsettingsd/xsettingsd.conf
```
我测试使用空的配置文件好像也行，不影响kde字体设置，gtk主体没有发现会改变

**Comment by xinghe98** [comment]
> @xinghe98
> `gnome-settings-daemon` 会破坏kde的字体设置，可以使用`xsettingsd`替代(包很小，依赖也少）
> 配置`xsettingsd`可以参考：https://github.com/derat/xsettingsd/wiki/Installation
> 配置文件默认在以下位置或者 `-c` 参数指定：
> 
> ```
> xsettingsd: Couldn't find config file. Tried the following:
>   ~/.xsettingsd
>   ~/.config/xsettingsd/xsettingsd.conf
>   /etc/xsettingsd/xsettingsd.conf
> ```
> 
> 我测试使用空的配置文件好像也行，不影响kde字体设置，gtk主体没有发现会改变

这对deepin-wechat确实可行，但我的deepin-tim会所有字体显示不出来，也许我是使用的空配置文件

**Comment by xinghe98** [comment]
@Face-Smile 
完美解决问题，重启后也不再需要重新设置，但tim会出故障需要重装，重装后的新版和wechat新版一样需要运行：
> env WINEPREFIX="$HOME/.deepinwine/Deepin-TIM" /usr/bin/deepin-wine winecfg
修改为windows xp 才不会报错

**Comment by countstarlight** [comment]
@Face-Smile 感谢帮助，已添加到[README](https://github.com/countstarlight/deepin-wine-wechat-arch/blob/master/README.md)和[run.sh](https://github.com/countstarlight/deepin-wine-wechat-arch/blob/master/run.sh#L101)

**Comment by amosbird** [comment]
![image](https://user-images.githubusercontent.com/5085485/79112564-69724000-7db1-11ea-97eb-eedf73f29a80.png)

请问这个字体算发虚吗？ 看着感觉有点别扭

**Comment by xz-dev** [comment]
@countstarlight 当没有配置文件时运行 xsettingsd 命令将失败
即提示 
```shell
xsettingsd: Couldn't find config file. Tried the following:
  ~/.xsettingsd
  ~/.config/xsettingsd/xsettingsd.conf
  /etc/xsettingsd/xsettingsd.conf
```
因此，当检测到命令失败时，应该自动运行 touch ~/.xsettingsd。否则，deepin-wine 将运行失败

**Comment by countstarlight** [comment]
@xz-dev 感谢帮助，已添加：https://github.com/countstarlight/deepin-wine-wechat-arch/commit/0cc2719c4107b1e9c758be3dce35d79e55352bfa
