### ISSUE TITLE
wine-4.21 版本是否可以正常模拟deepin-wine微信了

### ISSUE THREAD

**Issue by richwxd** [countstarlight/deepin-wine-wechat-arch#38]
原始版本的wine好事不能输入中文，有透明白边。deepin-wine是正常的。现在原始版本升级了，是否可以正常模拟呢

**Comment by countstarlight** [comment]
切换输入法问题在 wine 4.19已经解决：https://github.com/countstarlight/deepin-wine-wechat-arch/issues/31
边框问题切换到deepin-wine解决
