### ISSUE TITLE
屏幕上一直显示一个透明框

### ISSUE THREAD

**Issue by duanego** [countstarlight/deepin-wine-wechat-arch#39]
只要打开微信就会有一个透明框出现在屏幕中间。

opt/deepinwine/apps/Deepin-WeChat/run.sh
opt/deepinwine/tools/run.sh
/opt/deepinwine/tools/run_v2.sh
以上三个文件，WINE_CMD="deepin-wine"

无 ~/.local/share/applications/wine/Programs/WeChat

透明框如下图：
![image](https://user-images.githubusercontent.com/33107702/71407337-b3ee7600-2675-11ea-8643-82a4e8fe700e.png)

**Comment by duanego** [comment]
环境是manjaro-deepin

**Comment by kmvan** [comment]
那个其实不是透明框，是阴影。。。

**Comment by duanego** [comment]
只在第一次安装的时候有，第二天电脑重启再打开就没了........
