### ISSUE TITLE
v2.8.0.106-1+：文件，图片和视频发送有时候会失败

### ISSUE THREAD

**Issue by JadeRing** [countstarlight/deepin-wine-wechat-arch#42]
更新到deepin-wine-wechat 2.8.0.106-1 版本后, 微信自带的截图功能无法使用(但是通过QQ截的图,微信可以发送)
使用flameshot或manjaro自带的spectacle等截的图,也无法通过微信发送,
如图
![image](https://user-images.githubusercontent.com/38696086/72052579-63774980-3300-11ea-8932-5866a698a486.png)

plus: 此图是通过flameshot截的图

**Comment by ystyle** [comment]
我的是不管哪的图片，都很难发出去，或说要好几分钟才能发出去，就像图片上传链接被墙了上传速度几k一样。。。

**Comment by countstarlight** [comment]
看日志，是因为一个图片解码相关的库，应该发图片和收图片都会有问题:
```bash
0022:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0xb7eff3c,0xb28e768): stub
0022:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0xb7eff3c,0xb897788): stub
0022:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x97c1ef4,0xb897c28): stub
```
还在找解决办法

**Comment by szy132** [comment]
使用微信2.7.1.88可以发送，2.8.0.106 和2.8.0.110都不行  降级一下微信的版本就行 不知道是不是微信更新了啥

**Comment by jnzhanghs** [comment]
> 看日志，是因为一个图片解码相关的库，应该发图片和收图片都会有问题:
> 
> ```shell
> 0022:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0xb7eff3c,0xb28e768): stub
> 0022:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0xb7eff3c,0xb897788): stub
> 0022:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x97c1ef4,0xb897c28): stub
> ```
> 
> 还在找解决办法

接收没有问题，无法发送图片，不论是复制发送截图还是选文件发送图片或者转发图片都是失败。

**Comment by jnzhanghs** [comment]
> 看日志，是因为一个图片解码相关的库，应该发图片和收图片都会有问题:
> 
> ```shell
> 0022:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0xb7eff3c,0xb28e768): stub
> 0022:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0xb7eff3c,0xb897788): stub
> 0022:fixme:wincodecs:JpegDecoder_Frame_CopyPalette (0x97c1ef4,0xb897c28): stub
> ```
> 
> 还在找解决办法
文件发送也有小Bug，从窗口中打开file选文件会提示被占用。但是可以直接复制文件到聊天中发送

**Comment by countstarlight** [comment]
`2.8.0.121-1` 发送图片和文件问题好像解决了

**Comment by feileb** [comment]
更新到2.8.0.121-1测试图片发送正常

**Comment by JadeRing** [comment]
![image](https://user-images.githubusercontent.com/38696086/74522300-e1f58580-4f55-11ea-81a5-593b85543ef5.png)

试了下仍然不行啊

**Comment by JadeRing** [comment]
> `2.8.0.121-1` 发送图片和文件问题好像解决了

试了下,不行啊
![image](https://user-images.githubusercontent.com/38696086/74522386-094c5280-4f56-11ea-9f27-608b7706025c.png)

**Comment by ystyle** [comment]
一样不行。 还是和之前一样，几k的小图几秒能发，大一点的几乎发不出去

**Comment by luxl** [comment]
现在好像没有问题了，之前一直有问题，然后今天试了一下可以了。我用的是最新版的Manjaro

**Comment by Alice-space** [comment]
同该问题

**Comment by countstarlight** [comment]
建议暂时使用 [v2.7.1.88-1](https://github.com/countstarlight/deepin-wine-wechat-arch/releases/tag/v2.7.1.88-1)：
```bash
sudo pacman -U deepin-wine-wechat-2.7.1.88-1-x86_64.pkg.tar.xz
```
且确保在微信设置里关闭自动更新

**Comment by amosbird** [comment]
刚升级了 2.9.0.95  一样有文件发送不了的问题，图片倒是没问题，给 文件传输助手发送文件 也没问题

**Comment by BlindingDark** [comment]
> 刚升级了 2.9.0.95 一样有文件发送不了的问题，图片倒是没问题，给 文件传输助手发送文件 也没问题

我这边升级到 2.9.0.112，并不能发送图片。

**Comment by asd1614** [comment]
发送小图片不会有问题， 截图截大了， 就会发送不出去

**Comment by lexusking** [comment]
同问题，搜索了下，还没有找到解决方法

**Comment by wtfWSM** [comment]
同此问题，暂时用着2.7.188

**Comment by zishu-zy** [comment]
2.9.0.123版本依然存在这个问题

**Comment by lexusking** [comment]
发送图片失败的问题，还没有大佬可以解决吗？希望有大佬能解决 ，自己折腾了一下，还是搞不定。

**Comment by ety001** [comment]
> 发送图片失败的问题，还没有大佬可以解决吗？希望有大佬能解决 ，自己折腾了一下，还是搞不定。

只能暂时用 2.7.1.88

**Comment by jing2uo** [comment]
![图片](https://user-images.githubusercontent.com/3081432/85499906-11f41a00-b615-11ea-8022-1a25d8a47a88.png)

debian sid (当前 bullseye). 
Package: wine32:i386
Version: 5.0-4
wechat: 2.9.0.123
 
发送图片、文档、表格和压缩包都正常。
apt install playonlinux 方式安装，虚拟盘选择 system (之前一直是用自己从 pol 下的包)

**Comment by guxiwuruo** [comment]
> ![2020-06-24_12-29](https://user-images.githubusercontent.com/3081432/85500575-5c29cb00-b616-11ea-80c3-5fb065bc4f31.png)
> 
> debian sid (当前 bullseye).
> Package: wine32:i386
> Version: 5.0-4
> wechat: 2.9.0.123
> 
> 发送图片、文档、表格和压缩包都正常。
> apt install playonlinux 方式安装，虚拟盘选择 system (之前一直是用自己从 pol 下的包)

请问你是ubuntu安装playonlinux,然后再安装wechat吗？

**Comment by jing2uo** [comment]
@guxiwuruo  我是 debian apt 装的，ubuntu 差不多。用的这两天发现大图片(200k)会发送失败，小图可以正常发。还能接受。

**Comment by guxiwuruo** [comment]
> @guxiwuruo 我是 debian apt 装的，ubuntu 差不多。用的这两天发现大图片(200k)会发送失败，小图可以正常发。还能接受。

那文档表格压缩包正常吗？

**Comment by jing2uo** [comment]
@guxiwuruo  截图里测试了几个比较小的 doc excel pdf，猜测也是小文件可以，大文件过不去吧(和图片一样)。

**Comment by guxiwuruo** [comment]
> @guxiwuruo 截图里测试了几个比较小的 doc excel pdf，猜测也是小文件可以，大文件过不去吧(和图片一样)。

嗯嗯    谢谢回复。

**Comment by bpint** [comment]
@countstarlight 经试验，用deepin-wine5可解决此问题

**Comment by szy132** [comment]
@bpint @countstarlight  Arch 也可以了  而且打字文本框也可以跟随了
![image](https://user-images.githubusercontent.com/23374423/86914013-26c2c880-c152-11ea-8653-9ed08fd8d065.png)

yay -S deepin-wine5
vim /opt/deepinwine/apps/Deepin-WeChat/run.sh
![image](https://user-images.githubusercontent.com/23374423/86913775-b025cb00-c151-11ea-8d4d-97b2e6ee7c47.png)

如果使用sendkeys的话需要copy一个sendkeys.sh，这样不会影响到别的deepin-wine应用
vim /opt/deepinwine/tools/sendkeys-deepin-wine5.sh
![image](https://user-images.githubusercontent.com/23374423/86913855-dc414c00-c151-11ea-8e3d-19dcae4026aa.png)
![image](https://user-images.githubusercontent.com/23374423/86913905-f11ddf80-c151-11ea-8308-2fa56e97ad42.png)

**Comment by BlindingDark** [comment]
> 文本框也可以跟随

换用 deepin-wine5 之后，大图确实可以发送了。但是输入法我这里还是没办法跟随。

**Comment by JadeRing** [comment]
yay -S deepin-wine5
vim /opt/deepinwine/apps/Deepin-WeChat/run.sh

**Comment by JadeRing** [comment]
> > 文本框也可以跟随
> 
> 换用 deepin-wine5 之后，大图确实可以发送了。~但是输入法我这里还是没办法跟随。~ 第一次打字不能跟随，后面就可以了

me too

**Comment by lexusking** [comment]
majaro 使用 deepin-wine5 也解决了这个问题了

**Comment by jamninetyfive** [comment]
> majaro 使用 deepin-wine5 也解决了这个问题了

请教下 manjaro 解决问题的步骤，我安装了wine5 后还是不行～。

**Comment by lexusking** [comment]
> > majaro 使用 deepin-wine5 也解决了这个问题了
> 
> 请教下 manjaro 解决问题的步骤，我安装了wine5 后还是不行～。

方法一
1.安装deeping-wine5
2.从arch 上下载 deepin-wine-wechat 的 snapthot 包,解压修改PKGBUILD 文件中的 dependenies 里面 wine 为 deepin-wine5 , make -s 生成 安装包 再安装

方法二
1.如果你已经安装了 deepin-wine-wechat 最新版本了, 也安装了 deepin-wine5 了,直接修改vim /opt/deepinwine/apps/Deepin-WeChat/run.sh 里面的 WINE_CMD 为 deepin-wine5；这里面有个坑, 修改完了 deepin-wine5 后, 需要把 所有 winesever 的后台进程都干掉, 重启微信 才能使用 deepin-wine5 启动.

**Comment by jamninetyfive** [comment]
> > > majaro 使用 deepin-wine5 也解决了这个问题了
> > 
> > 
> > 请教下 manjaro 解决问题的步骤，我安装了wine5 后还是不行～。
> 
> 方法一
> 1.安装deeping-wine5
> 2.从arch 上下载 deepin-wine-wechat 的 snapthot 包,解压修改PKGBUILD 文件中的 dependenies 里面 wine 为 deepin-wine5 , make -s 生成 安装包 再安装
> 
> 方法二
> 1.如果你已经安装了 deepin-wine-wechat 最新版本了, 也安装了 deepin-wine5 了,直接修改vim /opt/deepinwine/apps/Deepin-WeChat/run.sh 里面的 WINE_CMD 为 deepin-wine5；这里面有个坑, 修改完了 deepin-wine5 后, 需要把 所有 winesever 的后台进程都干掉, 重启微信 才能使用 deepin-wine5 启动.

用了方法二。修改了 init里面的 deepin-wine5 然后结束了 所有wine的进程 重启了微信 也不行。。 还是大图发不出，几十k的可以。～

**Comment by bpint** [comment]
> > > > majaro 使用 deepin-wine5 也解决了这个问题了
> > > 
> > > 
> > > 请教下 manjaro 解决问题的步骤，我安装了wine5 后还是不行～。
> > 
> > 
> > 方法一
> > 1.安装deeping-wine5
> > 2.从arch 上下载 deepin-wine-wechat 的 snapthot 包,解压修改PKGBUILD 文件中的 dependenies 里面 wine 为 deepin-wine5 , make -s 生成 安装包 再安装
> > 方法二
> > 1.如果你已经安装了 deepin-wine-wechat 最新版本了, 也安装了 deepin-wine5 了,直接修改vim /opt/deepinwine/apps/Deepin-WeChat/run.sh 里面的 WINE_CMD 为 deepin-wine5；这里面有个坑, 修改完了 deepin-wine5 后, 需要把 所有 winesever 的后台进程都干掉, 重启微信 才能使用 deepin-wine5 启动.
> 
> 用了方法二。修改了 init里面的 deepin-wine5 然后结束了 所有wine的进程 重启了微信 也不行。。 还是大图发不出，几十k的可以。～

要看你的deepin-wine5装在哪里了。如果安装了多个版本的wine，只使用deepin-wine5这个命令并不能保证wineserver是deepin-wine5的，可以通过ps -Af | grep wineserver来验证是不是正确的版本。

对于系统里安装了多个版本wine的，至少要设置以下环境变量：

export WINEDLLPATH=/usr/lib/i386-linux-gnu/deepin-wine5
export WINELOADER=/usr/lib/i386-linux-gnu/deepin-wine5/wine
export WINESERVER=/usr/lib/i386-linux-gnu/deepin-wine5/wineserver

$WINELOADER "xxxx.exe"

当然，以上的路径要改成与系统相符的。

**Comment by lexusking** [comment]
> > > > majaro 使用 deepin-wine5 也解决了这个问题了
> > > 
> > > 
> > > 请教下 manjaro 解决问题的步骤，我安装了wine5 后还是不行～。
> > 
> > 
> > 方法一
> > 1.安装deeping-wine5
> > 2.从arch 上下载 deepin-wine-wechat 的 snapthot 包,解压修改PKGBUILD 文件中的 dependenies 里面 wine 为 deepin-wine5 , make -s 生成 安装包 再安装
> > 方法二
> > 1.如果你已经安装了 deepin-wine-wechat 最新版本了, 也安装了 deepin-wine5 了,直接修改vim /opt/deepinwine/apps/Deepin-WeChat/run.sh 里面的 WINE_CMD 为 deepin-wine5；这里面有个坑, 修改完了 deepin-wine5 后, 需要把 所有 winesever 的后台进程都干掉, 重启微信 才能使用 deepin-wine5 启动.
> 
> 用了方法二。修改了 init里面的 deepin-wine5 然后结束了 所有wine的进程 重启了微信 也不行。。 还是大图发不出，几十k的可以。～

直接执行一下  /opt/deepinwine/apps/Deepin-WeChat/run.sh  看看报错就知道了

**Comment by lexusking** [comment]
> > > > majaro 使用 deepin-wine5 也解决了这个问题了
> > > 
> > > 
> > > 请教下 manjaro 解决问题的步骤，我安装了wine5 后还是不行～。
> > 
> > 
> > 方法一
> > 1.安装deeping-wine5
> > 2.从arch 上下载 deepin-wine-wechat 的 snapthot 包,解压修改PKGBUILD 文件中的 dependenies 里面 wine 为 deepin-wine5 , make -s 生成 安装包 再安装
> > 方法二
> > 1.如果你已经安装了 deepin-wine-wechat 最新版本了, 也安装了 deepin-wine5 了,直接修改vim /opt/deepinwine/apps/Deepin-WeChat/run.sh 里面的 WINE_CMD 为 deepin-wine5；这里面有个坑, 修改完了 deepin-wine5 后, 需要把 所有 winesever 的后台进程都干掉, 重启微信 才能使用 deepin-wine5 启动.
> 
> 用了方法二。修改了 init里面的 deepin-wine5 然后结束了 所有wine的进程 重启了微信 也不行。。 还是大图发不出，几十k的可以。～

另外,修改 WINE_CMD 是在文件头的那个变量定义里面修改 ,不只是上面那个哥们的截图里只修改了 init 里面的这个

**Comment by jamninetyfive** [comment]
> > > > > majaro 使用 deepin-wine5 也解决了这个问题了
> > > > 
> > > > 
> > > > 请教下 manjaro 解决问题的步骤，我安装了wine5 后还是不行～。
> > > 
> > > 
> > > 方法一
> > > 1.安装deeping-wine5
> > > 2.从arch 上下载 deepin-wine-wechat 的 snapthot 包,解压修改PKGBUILD 文件中的 dependenies 里面 wine 为 deepin-wine5 , make -s 生成 安装包 再安装
> > > 方法二
> > > 1.如果你已经安装了 deepin-wine-wechat 最新版本了, 也安装了 deepin-wine5 了,直接修改vim /opt/deepinwine/apps/Deepin-WeChat/run.sh 里面的 WINE_CMD 为 deepin-wine5；这里面有个坑, 修改完了 deepin-wine5 后, 需要把 所有 winesever 的后台进程都干掉, 重启微信 才能使用 deepin-wine5 启动.
> > 
> > 
> > 用了方法二。修改了 init里面的 deepin-wine5 然后结束了 所有wine的进程 重启了微信 也不行。。 还是大图发不出，几十k的可以。～
> 
> 另外,修改 WINE_CMD 是在文件头的那个变量定义里面修改 ,不只是上面那个哥们的截图里只修改了 init 里面的这个

可以了 谢谢

完整步骤如下
1.修改/opt/deepinwine/apps/Deepin-WeChat/run.sh WINE_CMD 为deepin-wine5 保存
2.退出微信 
3.利用任务管理器杀死所有wine进程
4.重启微信。

**Comment by qiankun3** [comment]
> > > > > majaro 使用 deepin-wine5 也解决了这个问题了
> > > > 
> > > > 
> > > > 请教下 manjaro 解决问题的步骤，我安装了wine5 后还是不行～。
> > > 
> > > 
> > > 方法一
> > > 1.安装deeping-wine5
> > > 2.从arch 上下载 deepin-wine-wechat 的 snapthot 包,解压修改PKGBUILD 文件中的 dependenies 里面 wine 为 deepin-wine5 , make -s 生成 安装包 再安装
> > > 方法二
> > > 1.如果你已经安装了 deepin-wine-wechat 最新版本了, 也安装了 deepin-wine5 了,直接修改vim /opt/deepinwine/apps/Deepin-WeChat/run.sh 里面的 WINE_CMD 为 deepin-wine5；这里面有个坑, 修改完了 deepin-wine5 后, 需要把 所有 winesever 的后台进程都干掉, 重启微信 才能使用 deepin-wine5 启动.
> > 
> > 
> > 用了方法二。修改了 init里面的 deepin-wine5 然后结束了 所有wine的进程 重启了微信 也不行。。 还是大图发不出，几十k的可以。～
> 
> 要看你的deepin-wine5装在哪里了。如果安装了多个版本的wine，只使用deepin-wine5这个命令并不能保证wineserver是deepin-wine5的，可以通过ps -Af | grep wineserver来验证是不是正确的版本。
> 
> 对于系统里安装了多个版本wine的，至少要设置以下环境变量：
> 
> export WINEDLLPATH=/usr/lib/i386-linux-gnu/deepin-wine5
> export WINELOADER=/usr/lib/i386-linux-gnu/deepin-wine5/wine
> export WINESERVER=/usr/lib/i386-linux-gnu/deepin-wine5/wineserver
> 
> $WINELOADER "xxxx.exe"
> 
> 当然，以上的路径要改成与系统相符的。
> 
> 还有，“重启微信”并不是说只关掉微信界面(有时微信会残留进程)，而是要杀掉wine相关的过程。

请问deepin-wine5的winecfg怎么设置

**Comment by bpint** [comment]
> > > > > > majaro 使用 deepin-wine5 也解决了这个问题了
> > > > > 
> > > > > 
> > > > > 请教下 manjaro 解决问题的步骤，我安装了wine5 后还是不行～。
> > > > 
> > > > 
> > > > 方法一
> > > > 1.安装deeping-wine5
> > > > 2.从arch 上下载 deepin-wine-wechat 的 snapthot 包,解压修改PKGBUILD 文件中的 dependenies 里面 wine 为 deepin-wine5 , make -s 生成 安装包 再安装
> > > > 方法二
> > > > 1.如果你已经安装了 deepin-wine-wechat 最新版本了, 也安装了 deepin-wine5 了,直接修改vim /opt/deepinwine/apps/Deepin-WeChat/run.sh 里面的 WINE_CMD 为 deepin-wine5；这里面有个坑, 修改完了 deepin-wine5 后, 需要把 所有 winesever 的后台进程都干掉, 重启微信 才能使用 deepin-wine5 启动.
> > > 
> > > 
> > > 用了方法二。修改了 init里面的 deepin-wine5 然后结束了 所有wine的进程 重启了微信 也不行。。 还是大图发不出，几十k的可以。～
> > 
> > 
> > 要看你的deepin-wine5装在哪里了。如果安装了多个版本的wine，只使用deepin-wine5这个命令并不能保证wineserver是deepin-wine5的，可以通过ps -Af | grep wineserver来验证是不是正确的版本。
> > 对于系统里安装了多个版本wine的，至少要设置以下环境变量：
> > export WINEDLLPATH=/usr/lib/i386-linux-gnu/deepin-wine5
> > export WINELOADER=/usr/lib/i386-linux-gnu/deepin-wine5/wine
> > export WINESERVER=/usr/lib/i386-linux-gnu/deepin-wine5/wineserver
> > $WINELOADER "xxxx.exe"
> > 当然，以上的路径要改成与系统相符的。
> > 还有，“重启微信”并不是说只关掉微信界面(有时微信会残留进程)，而是要杀掉wine相关的过程。
> 
> 请问deepin-wine5的winecfg怎么设置

如果想运行winecfg，只要
```
$WINELOADER winecfg.exe
```
自带的winecfg是个shell脚本，可以参考

**Comment by SuperH-0630** [comment]
请问``TIM``是否也可以使用``deepin-wine5``呢？
我执行``more /opt/deepinwine/apps/Deepin-TIM/run.sh ``输出结果如下, 是否需要手动添加``WINE_CMD``
```
#!/bin/sh

#   Copyright (C) 2016 Deepin, Inc.
#
#   Author:     Li LongYu <lilongyu@linuxdeepin.com>
#               Peng Hao <penghao@linuxdeepin.com>

BOTTLENAME="Deepin-TIM"
APPVER="2.0.0deepin4"

/opt/deepinwine/tools/run.sh $BOTTLENAME $APPVER "$1" "$2" "$3"
```
我使用的是``manjaro``操作系统
谢谢

**Comment by amosbird** [comment]
用了 deepin-wine5 之后，窗口只能展示在上半个屏幕中。这是什么问题呢？

**Comment by lilydjwg** [comment]
> 用了 deepin-wine5 之后，窗口只能展示在上半个屏幕中。这是什么问题呢？

这个问题我用官方版本的 wine 也遇到过，大概是某个版本的 glibc / gcc / wine 有问题。后来更新之后就好了。

**Comment by amosbird** [comment]
用 deepin-wine5 是不是需要把 wine  wine-staging  deepin-wine 都卸载了呢？

**Comment by qiankun3** [comment]
还有一个问题，貌似png图片发不了，转成jpg就可以发

**Comment by bpint** [comment]
> 还有一个问题，貌似png图片发不了，转成jpg就可以发

可能是包的信赖关系不全。检查下这些包是否安装：

**Comment by countstarlight** [comment]
WeChat `3.0.0.57` 发送大图和文件的问题好像已经解决

**Comment by muyuuuu** [comment]
WeChat 3.3.0 不行，无法发送文件，且有阴影框。
