### ISSUE TITLE
yay 无法安装

### ISSUE THREAD

**Issue by Cyclone-Vox** [countstarlight/deepin-wine-wechat-arch#43]
yay 安装验证报错
==> 正在验证 source 文件，使用md5sums...
    deepin.com.wechat_2.6.2.31deepin0_i386.deb ... 通过
    WeChatSetup.exe ... 失败
    run.sh ... 通过
    reg.patch ... 通过

**Comment by qianlei90** [comment]
可以先从release中下载安装包，从本地安装：[README/用安装包安装](https://github.com/countstarlight/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

**Comment by Cyclone-Vox** [comment]
好的谢谢

**Comment by Cyclone-Vox** [comment]
> 可以先从release中下载安装包，从本地安装：[README/用安装包安装](https://github.com/countstarlight/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

好像还是不行按照文档说明的运行
 makepkg -si

依旧会md5 sum 然后
==> 正在验证 source 文件，使用md5sums...
    deepin.com.wechat_2.6.2.31deepin0_i386.deb ... 通过
    WeChatSetup.exe ... 失败
    run.sh ... 通过
    reg.patch ... 通过

**Comment by qianlei90** [comment]
下个老版本，比如[2.7.1.88-1](https://github.com/countstarlight/deepin-wine-wechat-arch/releases/download/v2.7.1.88-1/deepin-wine-wechat-2.7.1.88-1-x86_64.pkg.tar.xz)，然后

```
sudo pacman -U deepin-wine-wechat-2.7.1.88-1-x86_64.pkg.tar.xz
```

这样子行吗？

**Comment by GoodbyeNJN** [comment]
每次升级都时候都会遇到WeChatSetup.exe校验失败的问题，尝试删除下面两个文件后可正常升级，不知可否修改下脚本，安装完后自动删除。
```
rm -rf ~/.cache/yay/deepin-wine-wechat/WeChatSetup.exe
rm -rf /opt/deepinwine/apps/Deepin-WeChat/WeChatSetup.exe
```

**Comment by countstarlight** [comment]
已经修改为下载的微信安装包带上版本号，不会再出现md5校验问题

**Comment by JianleiZhang** [comment]
![image](https://user-images.githubusercontent.com/7637056/76143002-13bdc000-60ae-11ea-91c6-d69bc7e53298.png)
看到版本号了，但是……

**Comment by countstarlight** [comment]
@JianleiZhang 已更新：https://github.com/countstarlight/deepin-wine-wechat-arch/commit/1f52a4fa6c94f069d6c737b3d2d3239bc95dbeab

**Comment by hanjinfeng0309** [comment]
> @JianleiZhang 已更新：[1f52a4f](https://github.com/countstarlight/deepin-wine-wechat-arch/commit/1f52a4fa6c94f069d6c737b3d2d3239bc95dbeab)

版本2.9.5.56又出现了这个问题

**Comment by countstarlight** [comment]
@hanjinfeng0309 已更新：https://github.com/countstarlight/deepin-wine-wechat-arch/commit/0cc2719c4107b1e9c758be3dce35d79e55352bfa
