### ISSUE TITLE
Manjaro Arch linux - 2.8.0.116-1 - 打开微信后会新开一个Windows图标

### ISSUE THREAD

**Issue by peterzhang41** [countstarlight/deepin-wine-wechat-arch#45]
**打开微信后会新开一个Windows图标 然后实际APP是在那个Windows图标中使用**
我网上搜索了一下
把WeChat.exe改成wechat.exe就行
我目前装完后 执行这条命令
sudo sed -i "13s/WeChat.exe/wechat.exe/" /usr/share/applications/deepin.com.wechat.desktop

**Comment by countstarlight** [comment]
已经加上了：https://github.com/countstarlight/deepin-wine-wechat-arch/commit/7874ae6384ef2e4b61e22ac5a2d4e20d135f9368 (找不到你的email来签名这条commit)，我不能复现这个问题，等其他人反馈

**Comment by jimorsm** [comment]
修改deepin.com.wechat.desktop文件中的StartupWMClass
`StartupWMClass=wechat.exe`
测试过一个desktop文件可以有多个StartupWMClass

具体解释如下：
- [What does the StartupWMClass field of a .desktop file represent?](https://askubuntu.com/questions/367396/what-does-the-startupwmclass-field-of-a-desktop-file-represent)
- [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)

查询运行中的程序`WM_CLASS`值
![image](https://user-images.githubusercontent.com/3843791/73682906-3e59d900-46fc-11ea-9298-44ea2d0d036e.png)
