### ISSUE TITLE
arch新手请问，安装包安装的wechat如何卸载呢？

### ISSUE THREAD

**Issue by thep0y** [countstarlight/deepin-wine-wechat-arch#46]
因为2.8不能发送图片，已降为2.6了，如果这个问题能修复的话，还想着再更新回来，那时得先卸载2.6吧？请问该如何卸载呢？

**Comment by qianlei90** [comment]
`sudo pacman -Rns deepin-wine-wechat`

PS：可以用`man pacman`看下manpage中关于`-R`参数的介绍

**Comment by countstarlight** [comment]
更新不需要卸载旧版，和更新系统软件一样。从aur，本地打包和安装包安装的卸载方式都和@qianlei90 的方法一样：
```bash
sudo pacman -Rns deepin-wine-wechat
```
