### ISSUE TITLE
文件，图片和视频发送有时候会失败

### ISSUE THREAD

**Issue by Xusine1131** [countstarlight/deepin-wine-wechat-arch#47]
我刚开始以为是因为发送的文件过不了审核导致失败，但后来使用网页版时就可以正确发送。
目前无法排除是我自己账号的原因，但也没法确认到底是不是微信运行在wine中的原因。
微信版本2.8.0.121，wine的版本5.0.

**Comment by zhjsun** [comment]
同样的问题，换deepin-wine也不行

**Comment by ystyle** [comment]
我换 https://github.com/huan/docker-wechat 先用着了。
这个没问题，把启动脚本下载下来，把脚本中的
`$HOME/DoChat/WeChat Files/` 替换成自己的目录，聊天记录能保留下来

**Comment by archyly** [comment]
v2.7.1.88-1 版本是bug比较少的，使用的官方wine，除了发现不能截图外，其余功能暂时没发现问题。如果使用deepin-wine应该是可以完美运行的

**Comment by zhao-kun** [comment]
> 我刚开始以为是因为发送的文件过不了审核导致失败，但后来使用网页版时就可以正确发送。
> 目前无法排除是我自己账号的原因，但也没法确认到底是不是微信运行在wine中的原因。
> 微信版本2.8.0.121，wine的版本5.0.

和你一样的问题， 微信在 2.7.1 的时候是可以发送的，升级到2.8.0+ 后基本就没办法发送文件了。 （其实文件小于20k是可以，大文件不行， 不知道是原因）

**Comment by countstarlight** [comment]
建议暂时使用 [v2.7.1.88-1](https://github.com/countstarlight/deepin-wine-wechat-arch/releases/tag/v2.7.1.88-1)：
```bash
sudo pacman -U deepin-wine-wechat-2.7.1.88-1-x86_64.pkg.tar.xz
```

**Comment by countstarlight** [comment]
与 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/42 重复
