### ISSUE TITLE
建议官方把微信底包改为2.6.8.65

### ISSUE THREAD

**Issue by laomocode** [countstarlight/deepin-wine-wechat-arch#48]
如题，目前deepin团队已经发布这个版本的wine微信，是否考虑跟进？

在Arch Linux+Gnome+wine环境中，使用此版本底包发送图片的问题似乎得到了解决。

**Comment by countstarlight** [comment]
感谢提醒，已经更新：https://github.com/countstarlight/deepin-wine-wechat-arch/commit/f24b4f8f85f51c4359942c536a1f6a3c00e39be0
发送图片问题依然存在，和之前一样，只有运行后开始几次发送可能会成功
