### ISSUE TITLE
安装时密钥无法导入

### ISSUE THREAD

**Issue by Karl15926** [countstarlight/deepin-wine-wechat-arch#49]
如图，设备是Pixelbook的Crostini容器，ChromeOS的Linux子系统默认是Debian，我手动改成的Arch Linux
![Screenshot 2020-03-26 at 22 45 26](https://user-images.githubusercontent.com/33948470/77660307-1bd59500-6fb4-11ea-9fd9-08da5ca15a3d.png)

**Comment by countstarlight** [comment]
先使用：
```bash
sudo pacman -Sy
```
同步密钥试试？

**Comment by Karl15926** [comment]
啊，那天可能网络连接不行，同步密钥了好几遍也不行，昨天又同步了一下就可以了，感谢～
