### ISSUE TITLE
想知道有没有更新wine内微信的方法

### ISSUE THREAD

**Issue by TTTPOB** [countstarlight/deepin-wine-wechat-arch#5]
大大您好，我成功地运行起了微信表现良好。但是由于新版本微信加入了一个实用功能 ：休眠唤醒后自动重新同步消息，是2.6.5版本加入的。[官方更新日志见此](https://weixin.qq.com/cgi-bin/readtemplate?lang=zh_CN&t=page/faq/win/265/index&faq=win_265)
所以我很想更新到这个版本（或者更新）。另外，我在发送消息时似乎遇到了回车有时不管用的问题，不知道有没有办法解决。

**Comment by countstarlight** [comment]
在 设置 -> 关于微信 里检查更新，然后下载安装更新：
![wechat.exe_20190226145425.png](https://i.loli.net/2019/02/26/5c74e2f6ad5be.png)

**Comment by TTTPOB** [comment]
可以，没想到真的可以更新。。。wine程序我一般不敢点更新。。。
________________________________
