### ISSUE TITLE
关于打包依赖的一点小建议

### ISSUE THREAD

**Issue by SamLukeYes** [countstarlight/deepin-wine-wechat-arch#51]
亲测 manjaro deepin 用 deepin-wine 2.18_22-3 近乎完美运行（发图还是不行），tim 3.0 也运行良好，目前完全用不着原版的wine了。但我现在不能卸掉wine，不然我的微信和tim也要跟着卸掉了。也许可以在打包的把wine这个依赖改为可选依赖wine和deepin-wine，然后在安装的时候自动检测环境，如果只有deepin-wine则自动修改运行脚本为用deepin-wine运行。

**Comment by feileb** [comment]
pacman -Rdd wine

**Comment by countstarlight** [comment]
@SamLukeYes `deepin-wine` 不在Archlinux官方源中，对于新安装的系统需要额外的配置才能安装 `deepin-wine-wechat`，不能做到开箱即用

**Comment by sukanka** [comment]
我也有同样的问题，想要在切换到`deepin-wine` 之后，卸载掉原版的 `wine`，但是现在的问题是，卸载原版的 `wine` 会一起卸载掉 QQ 微信。（可以在`run.sh` 里面加一个卸载原版 `wine` 及其组件的功能)
另外，建议把 `wqy-microhei` 调成可选依赖，我有一份 Windows 字体，因此可以直接把 Windows 字体链接过去。

**Comment by countstarlight** [comment]
`deepin-wine-wechat` 从 `v3.3.5.42` 开始，默认使用AUR仓库 [deepin-wine6-stable](https://aur.archlinux.org/packages/deepin-wine6-stable/)，不再依赖 `wine`
