### ISSUE TITLE
md5 check

### ISSUE THREAD

**Issue by yang1c** [countstarlight/deepin-wine-wechat-arch#56]
==> Validating source files with md5sums...
    deepin.com.wechat_2.6.8.65deepin0_i386.deb ... Passed
    WeChatSetup-2.9.0.114.exe ... FAILED
    run.sh ... Passed
    reg.patch ... Passed
    shadow.exe ... Passed
==> ERROR: One or more files did not pass the validity check!
Failed to build deepin-wine-wechat

**Comment by Triple-Z** [comment]
I have tried to clean yay cache by:
```bash
$ yay -Sc
```

but it still not work.

**Comment by countstarlight** [comment]
感谢提醒，已更新：https://github.com/countstarlight/deepin-wine-wechat-arch/commit/93d413fa9068fa54ab978400d676293a5e3ef6bf

**Comment by aliwumi** [comment]
我是manjaro 21，也是一直报这个错
`WeChatSetup-2.9.0.114.exe ... FAILED`
