### ISSUE TITLE
在KDE桌面下边框会穿透显示

### ISSUE THREAD

**Issue by TTTPOB** [countstarlight/deepin-wine-wechat-arch#6]
如图，看上去十分难受
![wine bug](https://user-images.githubusercontent.com/19909103/53393757-2cde5c00-39d8-11e9-99a2-7d9c8cb118e9.png)

**Comment by lelelemonade** [comment]
![Screenshot_20190310_200706](https://user-images.githubusercontent.com/33286387/54084788-2bb21500-4370-11e9-98e9-f84ef5de6c40.png)
这里也是，求解决方案

**Comment by countstarlight** [comment]
这个问题暂时没有思路，已经发邮件请教wine forum的专业用户

**Comment by kmvan** [comment]
这个问题很好解决。只需要最大化当前微信窗口就好。。。

**Comment by XanthusL** [comment]
xfce+compton  也是这样

**Comment by nshusr** [comment]
manjaro deepin 也这样，可deepin官方的dde就没这问题，很奇怪，希望有解决这个的办法

**Comment by countstarlight** [comment]
参照 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/15#issuecomment-515455845 换用 `deepin-wine` 试试

**Comment by nshusr** [comment]
> 参照[＃15（评论）](https://github.com/countstarlight/deepin-wine-wechat-arch/issues/15#issuecomment-515455845)换用`deepin-wine`试试

deepin-wine 启用就完全正常了

**Comment by jimorsm** [comment]
使用 proton 可以解决, 微信主窗口不会出现边框穿透, 但是微信的子窗口还是会有边框穿透显现. 使用 proton 的好处在于可以用最新版微信. 
我是 Manjaro Gnome, 运行在 VMware 下.
![75103756-29f16800-563a-11ea-961c-0491d772931e](https://user-images.githubusercontent.com/3843791/75103835-928d1480-563b-11ea-8f15-fd4494653479.jpg)
![image](https://user-images.githubusercontent.com/3843791/75103846-c405e000-563b-11ea-9e54-25823f74fc60.png)

proton 可以在 AUR 里安装, 选择 proton-native. 

目前暂时的问题是无法输入中文

**Comment by countstarlight** [comment]
https://github.com/countstarlight/deepin-wine-wechat-arch/commit/1e33df5058e80df282be36b5dc6aac9afa091b05 解决，参照[#消除阴影边框](https://github.com/countstarlight/deepin-wine-wechat-arch#%E6%B6%88%E9%99%A4%E9%98%B4%E5%BD%B1%E8%BE%B9%E6%A1%86)
