### ISSUE TITLE
One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by SwordSing** [countstarlight/deepin-wine-wechat-arch#64]
报告一个用yay安装时候的错误

==> Validating source files with md5sums...
    deepin.com.wechat_2.6.8.65deepin0_i386.deb ... Passed
    WeChatSetup-2.9.5.41.exe ... FAILED
    run.sh ... Passed
    reg.patch ... Passed
    shadow.exe ... Passed
==> ERROR: One or more files did not pass the validity check!
error downloading sources: deepin-wine-wechat

**Comment by countstarlight** [comment]
感谢提醒，已更新：https://github.com/countstarlight/deepin-wine-wechat-arch/commit/eafd111141561d1bccfe3fcf3875f51e4b781b9d
