### ISSUE TITLE
高分辨率屏幕上字体太小, 不能跟随系统缩放

### ISSUE THREAD

**Issue by lixit** [countstarlight/deepin-wine-wechat-arch#68]
Manjaro Linux Gnome
27 inch 4k 显示器 200% 缩放下
字体太小

**Comment by countstarlight** [comment]
参照 [高分辨率屏幕支持](https://github.com/countstarlight/deepin-wine-wechat-arch#%E9%AB%98%E5%88%86%E8%BE%A8%E7%8E%87%E5%B1%8F%E5%B9%95%E6%94%AF%E6%8C%81)

**Comment by lixit** [comment]
请问这个是什么意思, 设置环境变量, 之后呢?

> 对于 deepin-wine ：
> 
> env WINEPREFIX="$HOME/.deepinwine/Deepin-WeChat" deepin-wine winecfg

**Comment by countstarlight** [comment]
这个不是环境变量，在终端中运行这条命令，会打开 `winecfg` 窗口，在Graphics选项卡中修改dpi

**Comment by lixit** [comment]
好的, 我没有中间的`deepin-wine`, 但运行下面的命令成功了.
> env WINEPREFIX="$HOME/.deepinwine/Deepin-WeChat"  winecfg

请问`deepin-wine`是命令吗? 还是文档有误

**Comment by yimiaoxiehou** [comment]
补充下，刚碰上同问题。  deepin-wine 是 deep的wine模拟器，不存在可能是有了新版本，我使用的deepin 23 使用的是 deepin-wine-6-stable.
使用 `env WINEPREFIX="$HOME/.deepinwine/Deepin-WeChat" deepin-wine6-stable winecfg` 即可修改微信的 wine 配置，如果修改分辨率直接调整 显示的屏幕分辨率就行了。
![image](https://github.com/vufa/deepin-wine-wechat-arch/assets/27064164/ded8c367-0a13-4533-8701-1d6dae87eed5)
