### ISSUE TITLE
关于字体

### ISSUE THREAD

**Issue by TTTPOB** [countstarlight/deepin-wine-wechat-arch#7]
> 默认使用文泉驿微米黑(wqy-microhei)字体，要使用其他字体，如 微软雅黑或者微软宋体放进`～/.deepinwine/Deepin-TIM/drive_c/windows/Fonts`中。

作者您好，我并没有明白上面这句话的意思，难道说我将字体放进去就会自动替换吗？还是说我需要将字体改名覆盖放入或是做一些其它的配置？我对wine非常不熟悉，希望您不吝赐教。

**Comment by countstarlight** [comment]
按照现在的配置是复制windows字体到fonts目录会对应生效，比如simsun，我在做wine tim和qq时用思源字体对应替换了微软雅黑和宋体，为了开箱即用，微信也可能这样做，届时不能再手动替换了
