### ISSUE TITLE
Manjaro KDE + 微信2.7.1.88 的多个问题

### ISSUE THREAD

**Issue by 1900011604** [countstarlight/deepin-wine-wechat-arch#70]
安装deepin-wine-wechat 2.7.1.88 之后将wine改为deepin-wine,有以下问题：

1. 原来的字体变小了！我的屏幕是surface pro 6的2736*1824，分辨率放大了125%，字体DPI是144，结果运行微信之后字体就变小了

![Screenshot_20200820_103307](https://user-images.githubusercontent.com/65082432/90710246-8e7f3e00-e2d0-11ea-837c-971d536ba1be.png)

**系统设置如图**

2.使用技能：
```
env WINEPREFIX="$HOME/.deepinwine/Deepin-WeChat" deepin-wine winecfg
```
更改微信分辨率不起作用，一直都很小

3.手机上的引用在电脑上不能显示（不知道是不是版本差距）

4.截图勾选“隐藏当前窗口”不起作用

5.改了微信号但是电脑还是显示旧的

6.用户名里面的表情显示不出来，事方框

7.打开小程序会显示这个网址：https://szsupport.weixin.qq.com/cgi-bin/mmsupport-bin/newreadtemplate?t=upgrade_common&pass_ticket=BUdZMH%2Fm76IHYvF1q9WSiBdutaetgkf625jXQV3euPEPyCNut3YuJY5QjP9DYfbc&wechat_real_lang=zh_CN

**Comment by 1900011604** [comment]
重启可解决第一个问题

**Comment by countstarlight** [comment]
* dpi 设置参照 README：[高分辨率屏幕支持](https://github.com/countstarlight/deepin-wine-wechat-arch#%E9%AB%98%E5%88%86%E8%BE%A8%E7%8E%87%E5%B1%8F%E5%B9%95%E6%94%AF%E6%8C%81)
* 微信功能问题尝试升级到最新版并[切换到 `deepin-wine`](https://github.com/countstarlight/deepin-wine-wechat-arch#%E5%88%87%E6%8D%A2%E5%88%B0-deepin-wine)
* 小程序暂不支持，转到：https://github.com/countstarlight/deepin-wine-wechat-arch/issues/60

**Comment by 1900011604** [comment]
现在我已经不用你们这个微信了，dpi应该调到200%
