### ISSUE TITLE
manjaro kde  打开微信后一直全屏占据整个屏幕，无法自由缩放微信大小

### ISSUE THREAD

**Issue by bladelei** [countstarlight/deepin-wine-wechat-arch#76]
只能进行最小化，无法正常的选中利用拖拽让微信尺寸变小

**Comment by countstarlight** [comment]
如何复现这个问题？

**Comment by bladelei** [comment]
> 如何复现这个问题？

现在只要打开微信它就会占据整个屏幕，这个算是一直复现着吗？

**Comment by loveDxq** [comment]
双击标题栏或者按照alt键拖动窗体呢，正常情况来说，这样会脱离最大化环境

**Comment by bladelei** [comment]
> 双击标题栏或者按照alt键拖动窗体呢，正常情况来说，这样会脱离最大化环境

尝试了，还有把卸载重装后试了下还是不行，总之谢谢哈

**Comment by bladelei** [comment]
刚更新后发现已经解决了这个bug，很稳很稳
