### ISSUE TITLE
打开联系人详细信息，窗口失去焦点

### ISSUE THREAD

**Issue by NIL-zhuang** [countstarlight/deepin-wine-wechat-arch#77]
* version : deepin-wine-wechat 2.9.5.56-1
* OS:  5.7.17-2-MANJARO

### 复现

1. 打开WeChat正常登陆
2. 进入某个聊天窗口，点击上方用户名（不是头像），进入详情页面
3. 退出联系人详情，或者尝试修改一下备注（这也不可以）
4. WeChat窗口失去焦点无法点击

一种可行的修复方法是右键任务栏图标，启动新实例，可以恢复窗口

**Comment by ety001** [comment]
目前来看只能按Esc关闭弹层。
