### ISSUE TITLE
正确的安装顺序？

### ISSUE THREAD

**Issue by 1900011604** [countstarlight/deepin-wine-wechat-arch#78]
我安装微信的顺序：
```
sudo pacman -U deepin-wine-wechat-2.7.1.88-1-x86_64.pkg.tar.xz
点击wechat安装

/opt/deepinwine/apps/Deepin-WeChat/run.sh -d
env WINEPREFIX="$HOME/.deepinwine/Deepin-WeChat" deepin-wine winecfg
调整DPI为192
```
然后wechat就点不开了
![Screenshot_20200916_084309](https://user-images.githubusercontent.com/65082432/93278976-ad51f100-f7f8-11ea-90e8-7d3c7ccb47ed.png)

**正确的安装顺序是什么？**

```
wechat 2.7.1.88
OS Manjaro 20.1
Kernel x86_64 Linux 5.8.8-arch1-1-surface
```

**Comment by 1900011604** [comment]
现在发现是必须安装微信后才能转换到deepin-wine

**Comment by countstarlight** [comment]
参照 [README](https://github.com/countstarlight/deepin-wine-wechat-arch#%E5%AE%89%E8%A3%85)，任选一种安装方式；打不开应该是其他错误导致，可以在终端中启动：
```bash
/opt/apps/com.qq.weixin.deepin/files/run.sh
```
看看导致不能启动的具体错误是什么

**Comment by 1900011604** [comment]
我现在已经不用你们这个微信了，这个issue也不再维护

**Comment by 1900011604** [comment]
PS: 2.7.1.88也不能用了吗？
