### ISSUE TITLE
problem installing deepin-wine-wechat

### ISSUE THREAD

**Issue by bingguo1** [countstarlight/deepin-wine-wechat-arch#85]
I already added archlinuxcn to my /etc/pacman.conf, and installed the keyring

$ yay -S deepin-wine-wechat
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  deepin-wine-wechat-3.0.0.57-1

  1 deepin-wine-wechat                       (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/bing/.cache/yay/deepin-wine-wechat
:: Downloaded PKGBUILD (1/1): deepin-wine-wechat
  1 deepin-wine-wechat                       (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: (1/1) Parsing SRCINFO: deepin-wine-wechat
==> Making package: deepin-wine-wechat 3.0.0.57-1 (Mon 02 Nov 2020 10:30:16 AM EST)
==> Retrieving sources...
  -> Downloading deepin.com.wechat_2.6.8.65deepin0_i386.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   142  100   142    0     0     64      0  0:00:02  0:00:02 --:--:--    64
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'packages.deepin.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
==> ERROR: Failure while downloading https://mirrors.ustc.edu.cn/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.8.65deepin0_i386.deb
    Aborting...
error downloading sources: deepin-wine-wechat

**Comment by countstarlight** [comment]
Hi, it seems that the ssl certificate of `packages.deepin.com` is incorrectly set to the certificate of `deepin.org`.  Now we can only wait for them to fix this problem, or you can install `deepin-wine-wechat` with the installation package from [GitHub Release](https://github.com/countstarlight/deepin-wine-wechat-arch/releases)

**Comment by countstarlight** [comment]
Fixed: https://github.com/countstarlight/deepin-wine-wechat-arch/commit/d5d1521aaa4adfdd4b27bafb03180acc4554f4e1
