### ISSUE TITLE
manjaro GNOME miss some dependencies

### ISSUE THREAD

**Issue by zshnb** [countstarlight/deepin-wine-wechat-arch#86]
my system info is
![image](https://user-images.githubusercontent.com/17894980/98191269-c868f380-1f53-11eb-8e2b-ebdd9a5a1cfe.png)
when i try to install wechat i encounter patch, binutils and fakeboot

**Comment by SamLukeYes** [comment]
Have you installed `base-devel`? You should always install this package group first before using AUR packages.

**Comment by zshnb** [comment]
> Have you installed `base-devel`? You should always install this package group first before using AUR packages.

no, so in your meaning when before install wechat under arch-linux user should always install `base-devel`?. and this is in README?

**Comment by SamLukeYes** [comment]
> > Have you installed `base-devel`? You should always install this package group first before using AUR packages.
> 
> no, so in your meaning when before install wechat under arch-linux user should always install `base-devel`?. and this is in README?

https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started

**Comment by zshnb** [comment]
> > > Have you installed `base-devel`? You should always install this package group first before using AUR packages.
> > 
> > 
> > no, so in your meaning when before install wechat under arch-linux user should always install `base-devel`?. and this is in README?
> 
> https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started

i see, thank you
