### ISSUE TITLE
Version 2.6.7?

### ISSUE THREAD

**Issue by kmvan** [countstarlight/deepin-wine-wechat-arch#9]
<del>https://dlglobal.qq.com/weixin/Windows/WeChat_C1018.exe</del>
抱歉，这个地址不是最新版的。我找一下官方的地址。
下面这个地址是爬出来的，但版本依然是 2.6.7.40,同上面的一样，但md5不同。
https://dlglobal.qq.com/weixin/Windows/WeChat_C1022.exe

内置更新后是2.6.7.57.这个下载的地址需要抓包才有，等会我抓一下更新的地址看看是不是安装包来的。

**Comment by countstarlight** [comment]
感谢你的帮助，这个链接可以下载到微信2.6.7吗？之后更新的版本要怎样找到这样固定的链接呢？

**Comment by kmvan** [comment]
这个我是在官网拷贝链接的，这个链接好像没什么规律。

微信我本地是安装官方最新版本的exe然后拷贝文件到deepin wine的微信目录里面，没任何修改就能覆盖更新正常运行了。

但 push 之前最好稍微测试一下，可能发行版不同有所不同。

**Comment by countstarlight** [comment]
好的，我去微信官网再仔细看看。测试在微信的设置->关于微信里直接更新也是可行的：[issue5](https://github.com/countstarlight/deepin-wine-wechat-arch/issues/5)

**Comment by countstarlight** [comment]
commit [ed6d2d1e4f17250df81b3d5fac2b4b05e361e69f](https://github.com/countstarlight/deepin-wine-wechat-arch/commit/ed6d2d1e4f17250df81b3d5fac2b4b05e361e69f)

**Comment by countstarlight** [comment]
@kmvan 在最近一次构建中，`WeChat_C1022.exe`的md5发生变化，这个不是对应指定版本的wechat吗？

**Comment by kmvan** [comment]
> @kmvan 在最近一次构建中，`WeChat_C1022.exe`的md5发生变化，这个不是对应指定版本的wechat吗？

https://dlglobal.qq.com/weixin/Windows/WeChat_C1022.exe

这个地址的版本号是一样的，但内容可能会发生变化，因为它的 md5 跟不同下载地址的 md5 不同。猜测不同时间生成的 exe md5 也不同。

**Comment by countstarlight** [comment]
> > @kmvan 在最近一次构建中，`WeChat_C1022.exe`的md5发生变化，这个不是对应指定版本的wechat吗？
> 
> https://dlglobal.qq.com/weixin/Windows/WeChat_C1022.exe
> 
> 这个地址的版本号是一样的，但内容可能会发生变化，因为它的 md5 跟不同下载地址的 md5 不同。猜测不同时间生成的 exe md5 也不同。

明白了，现在只能在md5变化时手动更新

**Comment by countstarlight** [comment]
新的 `WeChat_C1022.exe` WeChat 版本为`2.6.8.51`，为了固定版本，使用github release: [deepin-wine-wechat 2.6.8.51-1](https://github.com/countstarlight/deepin-wine-wechat-arch/releases/tag/v2.6.8.51-1)

**Comment by kmvan** [comment]
今天更新的版本提示：
`==> Validating source files with md5sums...
    deepin.com.wechat_2.6.2.31deepin0_i386.deb ... Passed
    WeChat_C1022.exe ... FAILED
    run.sh ... Passed
    reg.patch ... Passed
==> ERROR: One or more files did not pass the validity check!`

**Comment by countstarlight** [comment]
> 今天更新的版本提示：
> 
> > ==> Validating source files with md5sums...
> > deepin.com.wechat_2.6.2.31deepin0_i386.deb ... Passed
> > WeChat_C1022.exe ... FAILED
> > run.sh ... Passed
> > reg.patch ... Passed
> > ==> ERROR: One or more files did not pass the validity check!
> 
> md5...

这个md5很迷，在ci上也是错误的。但在本地构建和美国的vps上构建是没有问题的
