### ISSUE TITLE
更新到v3.0.0.57-2后无法启动

### ISSUE THREAD

**Issue by iiiuoye** [countstarlight/deepin-wine-wechat-arch#92]
测试环境：Manjaro 20.2  Deepin-wine5

启动后报错：The program (unidentified) has encountered a serious problem and needs to close. 

![2020-11-26_10-05](https://user-images.githubusercontent.com/35686959/100299588-009da800-2fcf-11eb-978c-3a56eb8bdfc3.png)

**Comment by iiiuoye** [comment]
Unhandled exception: page fault on read access to 0x000001b4 in 32-bit code (0x04d4a780).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:04d4a780 ESP:0031eed4 EBP:0031eee0 EFLAGS:00010202(  R- --  I   - - - )
 EAX:0031eefc EBX:00000000 ECX:000001b0 EDX:00000001
 ESI:04d42a10 EDI:000001b0
Stack dump:
0x0031eed4:  0042a000 04d42a10 00000000 0031eef0
0x0031eee4:  04d4fd5b 0031eefc 00000001 0031f108
0x0031eef4:  04d42a5a 0031eefc 0069006d 0062006e
0x0031ef04:  006e0074 00000000 00000000 00000000
0x0031ef14:  00000000 00000000 00000000 00000000
0x0031ef24:  00000000 00000000 00000000 00000000
Backtrace:
=>0 0x04d4a780 EntryPoint+0xffffffff() in wechatinstalldll (0x0031eee0)
  1 0x04d4fd5b EntryPoint+0xffffffff() in wechatinstalldll (0x0031eef0)
  2 0x04d42a5a EntryPoint+0xffffffff() in wechatinstalldll (0x0031f108)
  3 0x00402026 EntryPoint+0xffffffff() in wechatsetup-3.0.0.57 (0x0031f3dc)
0x04d4a780 EntryPoint+0xffffffff in wechatinstalldll: cmpl	$0,0x4(%edi)
Modules:
Module	Address			Debug info	Name (35 modules)
PE	  400000-  467000	Export          wechatsetup-3.0.0.57
PE	 4d30000- 4e58000	Export          wechatinstalldll
PE	 4e60000- 4eee000	Deferred        gdiplus
PE	10000000-10006000	Deferred        system
PE	46080000-460fd000	Deferred        riched20
PE	61580000-6158c000	Deferred        msls31
PE	61740000-61782000	Deferred        advapi32
PE	62b80000-62b88000	Deferred        api-ms-win-core-localization-l1-2-1
PE	62fc0000-6304d000	Deferred        rpcrt4
PE	63480000-6348c000	Deferred        version
PE	637c0000-63813000	Deferred        oleacc
PE	63bc0000-63bd9000	Deferred        shcore
PE	64a40000-64a94000	Deferred        shlwapi
PE	64ec0000-64fe8000	Deferred        oleaut32
PE	68500000-68559000	Deferred        combase
PE	68700000-6872e000	Deferred        uxtheme
PE	6a400000-6a52b000	Deferred        ole32
PE	6aa40000-6aa7e000	Deferred        usp10
PE	6ac80000-6ac87000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	6bc00000-6bc2a000	Deferred        sechost
PE	6bcc0000-6bd3e000	Deferred        setupapi
PE	6c9c0000-6cae8000	Deferred        gdi32
PE	6cc40000-6cda7000	Deferred        comctl32
PE	6d300000-6d308000	Deferred        shfolder
PE	6de80000-6de88000	Deferred        api-ms-win-core-synch-l1-2-0
PE	6ed00000-6ef1a000	Deferred        user32
PE	70e80000-70e8a000	Deferred        msimg32
PE	71200000-7121a000	Deferred        imm32
PE	7b000000-7b0e4000	Deferred        kernelbase
PE	7b600000-7b818000	Deferred        kernel32
PE	7bc00000-7bc9f000	Deferred        ntdll
PE	7cdb0000-7cdb4000	Deferred        msvcrt
PE	7d360000-7d364000	Deferred        winex11
PE	7db40000-7e417000	Deferred        shell32
PE	7e540000-7e544000	Deferred        ucrtbase
Threads:
process  tid      prio (all id:s are in hex)
00000020 (D) c:\Program Files\Tencent\WeChatSetup-3.0.0.57.exe
	00000024    0 <==
	000000f8    0
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	0000005c    0
	0000006c    0
	00000084    0
	000000a8    0
	000000d0    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	00000060    0
00000064 plugplay.exe
	00000068    0
	00000070    0
	00000074    0
	00000078    0
	00000094    0
0000007c winedevice.exe
	00000080    0
	00000088    0
	0000008c    0
	00000090    0
	0000009c    0
000000a0 svchost.exe
	000000a4    0
	000000ac    0
	000000b0    0
000000b4 explorer.exe
	000000b8    0
	000000bc    0
	000000c0    0
000000c8 rpcss.exe
	000000cc    0
	000000d8    0
	000000dc    0
	000000e0    0
	000000e4    0
	000000e8    0
System information:
    Wine build: wine-5.21
    Platform: i386
    Version: Windows 7
    Host system: Linux
    Host version: 5.9.10-1-MANJARO

**Comment by jianyestudy** [comment]
我也是

**Comment by GavinAndre** [comment]
同样碰到问题了

**Comment by Minxiao-Wang** [comment]
同样的问题

**Comment by 50ways2sayhard** [comment]
先把 deepin-wine-wechat 卸载掉，然后再将所有 wine 相关进程杀死，再重新安装 deepin-wine-wechat 就可以了。切换到 deepin-wine5 时也要杀死 wine 进程，然后切换完再杀一次，再打开就能正常用了

**Comment by iiiuoye** [comment]
> 先把 deepin-wine-wechat 卸载掉，然后再将所有 wine 相关进程杀死，再重新安装 deepin-wine-wechat 就可以了。切换到 deepin-wine5 时也要杀死 wine 进程，然后切换完再杀一次，再打开就能正常用了

试了... 我这还是不行...

**Comment by countstarlight** [comment]
在终端中用：
```bash
/opt/apps/com.qq.weixin.deepin/files/run.sh -d
```
切换到 `deepin-wine5` 后，直接在终端中启动：
```bash
/opt/apps/com.qq.weixin.deepin/files/run.sh
```
试试

**Comment by iiiuoye** [comment]
> 在终端中用：
> 
> ```shell
> /opt/apps/com.qq.weixin.deepin/files/run.sh -d
> ```
> 
> 切换到 `deepin-wine5` 后，直接在终端中启动：
> 
> ```shell
> /opt/apps/com.qq.weixin.deepin/files/run.sh
> ```
> 
> 试试

解决了.... 成功打开.... 谢谢!
