### ISSUE TITLE
3.0.0-52版本安装后中文无法正常显示

### ISSUE THREAD

**Issue by zshnb** [countstarlight/deepin-wine-wechat-arch#93]
系统：manjaro+GNOME
按照文档所说最新版本不需要安装文泉字体，但是我在启动后发现中文显示方块，尝试安装wqy-micro-hei后字体显示正常

**Comment by SimonZhongl** [comment]
thx,it fix the issuue. :-)

**Comment by SimonZhongl** [comment]
> 系统：manjaro+GNOME
> 按照文档所说最新版本不需要安装文泉字体，但是我在启动后发现中文显示方块，尝试安装wqy-micro-hei后字体显示正常

thx,it fix the issue. :-)

**Comment by faonecze** [comment]
我这边搜索不到`wqy-micro-hei`,我用`wqy-microhei`
```shell
sudo pacman -S wqy-microhei
```

**Comment by zshnb** [comment]
> 我这边搜索不到`wqy-micro-hei`,我用`wqy-microhei`
> 
> ```shell
> sudo pacman -S wqy-microhei
> ```

是的，就是这个，我打错了不好意思
