### ISSUE TITLE
微信输入框输入汉字为方块

### ISSUE THREAD

**Issue by xz-dev** [countstarlight/deepin-wine-wechat-arch#94]
按照[该 issue](https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/136#issuecomment-514585722) 的解决方法处理后解决
请开发者完善安装脚本 @countstarlight

**Comment by chengs2035** [comment]
貌似需要微软雅黑的字体。
[136](https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/136#issuecomment-517576733)
的方式成功了

> 其实很简单，复制windows的字体(c:\windows\fonts\sim*, ms*)到~/.deepinwine/Deepin-WeChat/drive_c/windows/Fonts，然后退出微信，在进入就好了，不需要其他设置

**Comment by munderline** [comment]
按照二楼方法成功了， 具体操作如下：

# 1. [下载这个](https://www.fonts.net.cn/font-30931224951.html) 
# 2.将解压后的字体**WeiRuanYaHei-1.ttf**，复制到此路径下`~/.deepinwine/Deepin-WeChat/drive_c/windows/Fonts`

**Comment by zw963** [comment]
> 按照二楼方法成功了， 具体操作如下：
> # 1. [下载这个](https://www.fonts.net.cn/font-30931224951.html)
> # 2.将解压后的字体**WeiRuanYaHei-1.ttf**，复制到此路径下`~/.deepinwine/Deepin-WeChat/drive_c/windows/Fonts`

Arch linux 按照此种方式解决， 不过，为什么老一点的版本(几个月前) 没有此类问题？

**Comment by munderline** [comment]
> > 按照二楼方法成功了， 具体操作如下：
> > # 1. [下载这个](https://www.fonts.net.cn/font-30931224951.html)
> > # 2.将解压后的字体**WeiRuanYaHei-1.ttf**，复制到此路径下`~/.deepinwine/Deepin-WeChat/drive_c/windows/Fonts`
> 
> Arch linux 按照此种方式解决， 不过，为什么老一点的版本(几个月前) 没有此类问题？ 还有，好像 deepin-wine-qq 也没有类似问题？

可能是升级了deepin-wine5 吧, 具体的我也不清楚

**Comment by kingcanfish** [comment]
> > 按照二楼方法成功了， 具体操作如下：
> > # 1. [下载这个](https://www.fonts.net.cn/font-30931224951.html)
> > # 2.将解压后的字体**WeiRuanYaHei-1.ttf**，复制到此路径下`~/.deepinwine/Deepin-WeChat/drive_c/windows/Fonts`
> 
> Arch linux 按照此种方式解决， 不过，为什么老一点的版本(几个月前) 没有此类问题？ 还有，好像 deepin-wine-qq 也没有类似问题？

感谢

**Comment by maoxuner** [comment]
把系统安装的文泉驿雅黑软链接到微信wine的fonts目录也可以
```bash
pacman -S wqy-microhei
ln -s /usr/share/fonts/wenquanyi/wqy-microhei/wqy-microhei.ttc .deepinwine/Deepin-WeChat/drive_c/windows/Fonts/
```

**Comment by countstarlight** [comment]
`v3.2.1.151-1` 开始已经默认将 `wqy-microhei` 字体文件链接到 `WINEPREFIX` 环境

**Comment by Randool** [comment]
升级到deepin-wine-wechat 3.4.0.38-4后，输入框汉字变方块的问题又出现了。

`~/.deepinwine/Deepin-WeChat/drive_c/windows/Fonts`目录下有`arial.ttf`，`msyh.ttf`，`WeiRuanYaHei-1.ttf`，`wqy-microhei.ttc`四个文件，但是还是出现了方块。

![image](https://user-images.githubusercontent.com/20062080/144028435-0e8c19af-45f1-4808-b6a3-03ab6a8af8e9.png)

**Comment by liufeng** [comment]
遇到和Randool同样的问题。

**Comment by kgbook** [comment]
修改注册表中的部分字体，路径：*～/.deepinwine/Deepin-WeChat/system.reg*， patch 如下：
```bash
$ diff system.reg system.reg.backup
< "MS Sans Serif"="Z:\\usr\\share\\fonts\\TTF\\micross.ttf"
< "MS Serif"="Z:\\usr\\share\\fonts\\TTF\\micross.ttf"
---
> "MS Sans Serif"="sseriff.fon"
> "MS Serif"="serife.fon"
```

sseriff.fon  字体我 arch 环境 /*usr/share/fonts* 目录中是没有的。
```bash
$ find /usr/share/fonts -name sseriff.fon
$
```

修改 *system.reg* 替换为 *micross.ttf* 或其它中文字体，问题解决。
自己注意下符号链接的盘符，我的 `root` 分区被映射成 `Z` 盘，因此路径是 *"Z:\\usr\\share\\fonts\\TTF\\micross.ttf"*。
或中文字体拷贝到 *~/.deepinwine/Deepin-WeChat/drive_c/windows/Fonts* 目录后再使用相对路径.

**Comment by kbdancer** [comment]
> 遇到和Randool同样的问题。

Linux系统安装一下微软雅黑字体即可

**Comment by liufeng** [comment]
msyh.ttf 
不就是雅黑字体？应该都已经安装了。我发现刚启动的时候，输入光标是比较长的那种，这个时候输入中文没问题。如果这时按下退格键，光标会变短，这个时候只显示英文正常，中文就变成了细长的方框。趁光标还长的时候，输入一个汉字，之后就不会发生显示问题了。一旦光标变成短的，就只有重启微信一条路了。

在 2021年12月月24日 五 02时44分22秒 -0800，一只猿 
***@***.***> 写道：

**Comment by BreakingLead** [comment]
用qq也有这个问题

**Comment by liufeng** [comment]
目前的中文输入问题好多了，没输入的时候按退格键不会造成无法输入中文的情况，只有输入了英文字符才会无法输入中文。这时可以切换另一个聊天联系人，再切换回来，输入一个汉子就不会有问题了。

当然，如果可以根除问题就完美了。

发自我的iPhone
